### PR TITLE
Only build macOS and other Linux targets on stable branch

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
I've used this "misfeature" before now, to check more platforms, I'm not sure I want this change.  Let me think about it.

**Comment by tesuji** [comment]
In that case, you can remove `if` condition lines.

**Comment by tesuji** [comment]
Ping @kinnison, what do you think again?

**Comment by kinnison** [comment]
OK my thought is as follows:

PRs:

* Linux x86_64
* Linux ARM of some kind
* MacOS X x86_64
* Windows x86_64 MSVC

Master:

* Linux x86_64
* Linux ARM of some kind
* MacOS X x86_64
* Windows x86_64 MSVC
* Windows x86_64 GNU

Other branches within rustup (so stable etc) the full panel, but where `stable` is the only one doing a deploy to dev-static.

This will need appveyor changes as well as travis changes.

What do you think?

**Comment by kinnison** [comment]
And now that I've seen it - all should run the centos check too

**Comment by kinnison** [comment]
I think this is resolved with the recent merge to master of travis changes which includes early Windows support

**Pull request closed without merging**
