### PR TITLE
ci(windows): don't install `awscli` via `choco`

### PR DESCRIPTION
**Pull request by rami3l**
TLDR: Addresses https://github.com/rust-lang/rustup/pull/4105#issuecomment-2537797422.

It's not our problem, but `choco upgrade awscli` has been causing our `master` CI to fail since a few days ago:

```console
Progress: 100% - Completed download of C:\Users\runneradmin\AppData\Local\Temp\chocolatey\awscli\2.22.13\AWSCLIV2-2.22.13.msi (40.56 MB).
Download of AWSCLIV2-2.22.13.msi (40.56 MB) completed.
Hashes match.
Installing awscli...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\awscli_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\awscli\2.22.13\AWSCLIV2-2.22.13.msi" /qn /norestart /l*v "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\awscli.2.22.13.MsiInstall.log"] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\awscli_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The upgrade of awscli was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\awscli\tools\chocolateyinstall.ps1'.
 See log for details.
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - awscli (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\awscli\tools\chocolateyinstall.ps1'.
 See log for details.
Error: Process completed with exit code 1.
```

... and I guess the only reasonable thing to do now is stop using that command. Instead, we should just check whether `awscli` is already installed, like we currently do on Linux.

### CODE REVIEW

**Review by ChrisDenton — APPROVED** [review]
Makes sense to me. In any case, if it's already installed then we don't need to do anything.

**Comment by rami3l** [comment]
> Makes sense to me. In any case, if it's already installed then we don't need to do anything.

@ChrisDenton I believe it was there because sometimes inconsistent `awscli` versions between different runners will also cause problems for us... Now I really don't know since GitHub is constantly changing the list of software being installed and how each piece of software is managed in the system. Let's hope the actual release will be alright 🙏 I've scheduled it for this weekend.

**Comment by ChrisDenton** [comment]
> I believe it was there because sometimes inconsistent awscli versions between different runners will also cause problems for us...

Would that not be an issue for Linux runners too?

**Comment by rami3l** [comment]
> > I believe it was there because sometimes inconsistent awscli versions between different runners will also cause problems for us...
> 
> Would that not be an issue for Linux runners too?

@ChrisDenton That's a very good question 🤣 
- https://github.com/rust-lang/rustup/pull/3786
- https://github.com/rust-lang/rustup/pull/3989

**Pull request merged**
