### PR TITLE
Use backticks in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pickfire**
Suggested by @lzutao

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
Good catch.  I wonder if there's a sensible markdown lint we could run as part of the general checks CI job?

**Comment by tesuji** [comment]
> sensible markdown lint

Clippy [uses remarkjs](https://github.com/rust-lang/rust-clippy/blob/71a5379bda71f19539dabac0232330561e19be1a/.remarkrc), but it will include nodejs to build setup.

**Comment by kinnison** [comment]
I'd rather not add that kind of dependency in unless it's quick to install, but it is something to consider, thanks.

**Comment by tesuji** [comment]
It seems really fast to install on github actions: https://github.com/rust-lang/rust-clippy/runs/1065196865?check_suite_focus=true
But I'm not sure remarkjs could catch issue like this, because I've never used it locally.

**Comment by pickfire** [comment]
Heh, time to rewrite it in rust.

**Pull request merged**
