### PR TITLE
Fixing janky line breaks in self_updater.rs

### LINKED ISSUE #2343: Poor line breaks on Windows
Installing rustup today, I got this:

image

as you can see, there's a `\n` after `PATH` that causes the output to be less than ideal.

### PR DESCRIPTION
**Pull request by VladKou**
Fixes #2343 #2334   -  janky line breaks in the %USERPROFILE% path help string.

New line breaks:

image

### CODE REVIEW

**Comment by kinnison** [comment]
I'm fine with this rearrangement but you need to clean up your commits into a single neat commit please, I won't merge it in its current state.

**Comment by VladKou** [comment]
Coming from the p4 world, squishing commits in git's being a bit of a nightmare. 

Should I close this PR, wipe out my local branch, and try again?

**Comment by workingjubilee** [comment]
You can do that, but
I would suggest you pop off the merge commit you did and use `git rebase -i HEAD~5`
this will drop you into a text editor to run an interactive rebase on the last ~5 commits and squash the ones you want to squash. then you can `git push --force` and maybe `git pull origin master --rebase` to get back up to current.

**Comment by kinnison** [comment]
If you are unable to get it to work (it's a skill you'll want going forward, and I know how confusing it can be at first) then let me know and I'll rebase it for you.

**Comment by VladKou** [comment]
Yes, git's a valuable skill, and I'll give it some time today to figure this out. I appreciate your patience.

**Comment by kinnison** [comment]
This work needs rebasing again, and the commit sequence cleaning up.  We just released 1.22.0 and it'd be nice to get this fixed by 1.23.0

**Comment by rbtcollins** [comment]
I've done a rebase, as far as I can tell only the last commit was the actual content; the branch is https://github.com/rust-lang/rustup/pull/2420

**Comment by kinnison** [comment]
I think it was more that the first few commits were the real content, the rest was a merge commit mess.

**Pull request closed without merging**
