### PR TITLE
Bump version number

### PR DESCRIPTION
**Pull request by Diggsey**

### CODE REVIEW

**Comment by alexcrichton** [comment]
This should be fine to merge when ready, after merging to `master` you'll want to push the `stable` branch, and when that's done I can do the rigamarole of publishing the release

**Comment by Diggsey** [comment]
@alexcrichton we currently have two failing bors tests (powerpc64le and netbsd) both of which appear to be caused by rustc issues. Is that going to be a problem?

**Comment by mati865** [comment]
powerpc64le issue is basically: https://github.com/rust-lang/rust/issues/50499
It will be fixed in next stable (1.28).

NetBSD is more tricky, `setvbuf` should be available in system libc. Maybe bot is too old?

**Comment by Diggsey** [comment]
@alexcrichton I've merged and pushed to stable anyway

**Comment by alexcrichton** [comment]
Ok! It's probably fine to drop some of those platforms

**Comment by alexcrichton** [comment]
Ok published now!

**Comment by Diggsey** [comment]
Thanks!

**Pull request merged**
