### PR TITLE
Unwrap Option<Path> early and use Cow::into_owned

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by kinnison** [comment]
This commit conflates two changes -- one as described (unwrapping the `Option<Path>`) and one which replaces uses of `.to_string_lossy()` with `.display().to_string()`.

**Comment by tesuji** [comment]
Okay. I dropped the `.display().to_string()` changes.

**Comment by kinnison** [comment]
If you could tweak the commit message of the second commit, and update the PR title, then I think this could be merged.  (You have `Cown` where you meant `Cow`, and with the two commits, the PR title is now incorrect)

**Review by kinnison — APPROVED** [review]
:+1:

**Pull request merged**
