### PR TITLE
Unit test optimisation

### PR DESCRIPTION
**Pull request by rbtcollins**
More faster gooderer

### CODE REVIEW

**Comment by kinnison** [comment]
I'm slightly confused - this says unit test but afaict all the tests changed are integration tests.  The test content itself looks okay though.

**Comment by kinnison** [comment]
I've kicked the tests off again since apparently things should be fixed now.

**Comment by kinnison** [comment]
:+1: to merge on green CI

**Comment by rbtcollins** [comment]
Sorry yes, It was in my branch for making unit tests out of integration tests.

**Pull request merged**
