### PR TITLE
Workspaces

### PR DESCRIPTION
**Pull request by nrc**
This is mostly moving files around and adjusting paths in response. The idea is for Rustup to have a 'standard' workspaces layout, rather than the weird mix of one workspace plus a bunch of non-workspace crates.

It is failing a test locally (`uninstall_self_delete_works`), so I thought I'd get some extra eyes on it. It needs some high-level docs about how to build/test before it is ready to land.

r? @alexcrichton  @Diggsey

### CODE REVIEW

**Comment by nrc** [comment]
Hmm, I think that test might fail anyway for me

**Comment by alexcrichton** [comment]
@bors: r+

👍

**Comment by nrc** [comment]
```
     Running target\i686-pc-windows-msvc\release\deps\rustup_msi-a90ae371926d022c.exe
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
if defined BUILD_MSI pushd src\rustup-win-installer && cargo build --release --target %TARGET% & popd
The system cannot find the path specified.
Command exited with code 1
```

**Comment by alexcrichton** [comment]
I think `src\rustup-win-installer` no longer exists?

**Comment by nrc** [comment]
CLsoing since I haven't had time to rebase and it is now way out of date

**Pull request closed without merging**
