### PR TITLE
Make clippy happy

### PR DESCRIPTION
**Pull request by 0xPoe**
Most of them are for needless_borrow.

### CODE REVIEW

**Comment by 0xPoe** [comment]
cc: @rbtcollins @kinnison Could you please take a look? Thanks!

**Review by kinnison — APPROVED** [review]
I think these all look good.

**Comment by kinnison** [comment]
In the future, if you split this kind of thing up into multiple commits, it's easier to review.

**Comment by 0xPoe** [comment]
> In the future, if you split this kind of thing up into multiple commits, it's easier to review.

Got it. I will split this kind of thing up into multiple commits next time. Thanks for your review.

**Pull request merged**
