### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mati865**
This PR fixes all the warnings, tested on Linux.

### CODE REVIEW

**Comment by mati865** [comment]
Issues revealed by CI:
- 32bit *-linux-androideabi failure: https://github.com/Stebalien/xattr/issues/18
- 64bit *-linux-android: fixed by https://github.com/rust-lang-nursery/net2-rs/commit/d958a03dea71f3b2315adc0167bda6aa63c081c9, new release was made recently with fix
- powerpc64le-unknown-linux-gnu: https://github.com/rust-lang/rust/issues/50499
  <details>
  <summary>LLVM error (click here to expand)</summary>

  ```
  LLVM ERROR: Cannot select: 0x7f006fa7d0d0: ch = PPCISD::STBRX<ST6[%675](align=1)>   0x7f006e017840, 0x7f006e1939c0, 0x7f006e0167b8, ValueType:ch:i48
  0x7f006e1939c0: i32 = truncate 0x7f006e193068
    0x7f006e193068: i64 = srl 0x7f006e016680, Constant:i32<16>
      0x7f006e016680: i64 = or 0x7f006e224f70, 0x7f006fa45b60
        0x7f006e224f70: i64,ch = CopyFromReg 0x7f006e017840, Register:i64 %249
          0x7f006e016000: i64 = Register %249
        0x7f006fa45b60: i64 = shl nuw nsw 0x7f006e193410, Constant:i32<16>
          0x7f006e193410: i64 = AssertZext 0x7f006e016af8, ValueType:ch:i8
            0x7f006e016af8: i64,ch = CopyFromReg 0x7f006e017840, Register:i64 %252
              0x7f006e1936e8: i64 = Register %252
          0x7f006e016bc8: i32 = Constant<16>
      0x7f006e016bc8: i32 = Constant<16>
  0x7f006e0167b8: i64,ch = CopyFromReg 0x7f006e017840, Register:i64 %200
    0x7f006e016f70: i64 = Register %200
  In function: _ZN6base646decode6decode17hddc925063b1fb17bE
  error: Could not compile `hyper`.
  ```
  </details>

- x86_64-unknown-netbsd 
  <details>
  <summary>libc issue? (click here to expand)</summary>

  ```
  note: /usr/local/lib/gcc/x86_64-unknown-netbsd/5.3.0/../../../../x86_64-unknown-netbsd/bin/ld: /src/target/x86_64-unknown-netbsd/release/deps/libopenssl_sys-5b5efcbe61655b57.rlib(randfile.o): undefined reference to symbol 'setvbuf'
          /usr/local/x86_64-unknown-netbsd/lib/libc.so.12: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
  ```
  </details>

EDIT: I'll bump dependencies again to see how much it helps when I get some time.
EDIT2: Linked upstream issue for PowerPC64LE

**Comment by mati865** [comment]
Rebased with newer versions.
Android 64bit should get as far as 32bit now, it still needs fixing in `libc` or `xattr` crates.
PowerPC64LE and NetBSD will most likely fail again.

**Comment by Stebalien** [comment]
xattr v0.2.2 should fix builds on unsupported platforms

**Comment by mati865** [comment]
@Stebalien thank you for fix and notification.

PR rebased with updated `xattr` and other minor bumps, PowerPC64LE issue will be fixed in Rust 1.28.
Updating `hyper` to 0.12 could workaround the issue but it would be breaking change.

**Pull request merged**
