### PR TITLE
Improve OS detection of rustup-init.sh

### LINKED ISSUE #1946: Incorrect detection on Debian/Buster
I set about installing `rustup` onto a Debian/buster system and saw the following:

```shell
somniloquy% curl https://sh.rustup.rs/ | sh                                    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10652  100 10652    0     0  60522      0 --:--:-- --:--:-- --:--:-- 60522
info: downloading installer
Warning: Detected OS X platform older than 10.13
Warning: Not forcing TLS v1.2, this is potentially less secure

Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.
…
```

Seems we're incorrectly identifying Debian as OS-X somehow?

### PR DESCRIPTION
**Pull request by Rudi3**
An attempt to fix https://github.com/rust-lang/rustup.rs/issues/1946.

Checks if `$ARCH` contains `"darwin"` before checking the the existence of `sw_vers` and the software version of an alleged darwin os.

### CODE REVIEW

**Comment by Rudi3** [comment]
I'll fix the `dash` incompatibility soon!

**Comment by kinnison** [comment]
Given I discovered that #1946 was a bad issue (my fault) I'm not sure we need this.

**Comment by Rudi3** [comment]
Maybe not, but you may not wan't to solely rely on the existence of `sw_vers` to detect darwin as it can "easily" be fooled. `$ARCH` should be more reliable. On the other hand, it should not be **that** likely to have a fake `sw_vers`. ^^

**Comment by kinnison** [comment]
Fair, I'll give this a bit more of a ponder.  Belt and braces can't hurt I suppose.

**Comment by kinnison** [comment]
I'm not sure I like the amount of code churn needed to have the global `$ARCH` but I also don't like the idea of having to call `get_architecture` from multiple places.  It'd be non-trivial to thread `$_arch` through all the calls, leaving the possibility of just checking `$(uname -s)` in the `check_help_for` function.  I remain unsure which approach is best over-all because we abstracted uname checking into `get_architecture` for a reason.  I'm not going to make a call on this yet, but if you could come up with a way to minimise the change while having the same effect, I'd like to see a reduced patch.

**Comment by kinnison** [comment]
I remain uncomfortable with this change.  If a reduced scope patch is produced I'll consider it, otherwise I'll close this PR soon.  Thank you for caring enough to try and fix this.

**Comment by rbtcollins** [comment]
its pretty trivial really.

_arch -> downloader -> check_help_for. Its one code path, one variable.

**Comment by Rudi3** [comment]
Yes, I could just pass it through like you suggested. I'll try that soon.

**Review by kinnison — COMMENTED** [review]
This looks plausible.  I'm not in a position to fully review the change right now, but I shall endeavour to do so soon.  My gut feeling says this could be merged now.

**Comment by kinnison** [comment]
I apologise for the delay, my December was crazy and then I was unwell.  :+1:

**Comment by kinnison** [comment]
I've rebased your branch.  Assuming this passes CI, I'll merge.

**Pull request merged**
