### PR TITLE
rustup-init.sh: Fall back to less secure download

### LINKED ISSUE #1794: curl: option --proto: is unknown on CentOS 6
**Problem**
curl error when using: curl https://sh.rustup.rs -sSf | sh -s -- -y
```
docker run -it centos:6 /bin/bash
[root@081cc8b7180c /]# curl
curl: try 'curl --help' or 'curl --manual' for more information
[root@081cc8b7180c /]# curl https://sh.rustup.rs -sSf | sh -s -- -y
info: downloading installer
curl: option --proto: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.fBaoqs014w/rustup-init
```
Expected (this worked until 4 days ago):
```
curl https://sh.rustup.rs -sSf | sh -s -- -y
info: downloading installer
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-04-11, rust version 1.34.0 (91856ed52 2019-04-10)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'stable'

  stable installed - rustc 1.34.0 (91856ed52 2019-04-10)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
```

**Steps**

1. docker run -it centos:6 /bin/bash
2. curl https://sh.rustup.rs -sSf | sh -s -- -y

**Possible Solution(s)**
N/A

**Notes**

Output of `rustup --version`: N/A
Output of `rustup show`: N/A

### PR DESCRIPTION
**Pull request by kinnison**
If we're using OS X less than 10.13 or any platform where
curl or wget fail to advertise the required command line arguments
then fall back to not passing the flags to force TLSv1.2

This should fix #1794

Signed-off-by: Daniel Silverstone <dsilvers@digital-scurf.org>

### CODE REVIEW

**Comment by kinnison** [comment]
r? @alexcrichton @victorjulien @Eric-Arellano

I think this ought to solve the problems you all reported, but I'd really appreciate it if it were possible for you to test before I merge this.

**Comment by cosmicexplorer** [comment]
I will put up a test for this in the pantsbuild/pants repo in the next 30 minutes.

**Comment by victorjulien** [comment]
@kinnison happy to test but I will need some instructions on how to test it. Not familiar with your dev and qa process.

**Comment by kinnison** [comment]
@victorjulien If you could download https://github.com/kinnison/rustup.rs/blob/kinnison/retry-less-secure/rustup-init.sh and try it in CentOS 6 somehow then that'd help enormously

**Comment by victorjulien** [comment]
Looks good:
```
[root@424c5ff490c8 /]# ./rustup-init.sh -y
info: downloading installer
Warning: Not forcing TLS v1.2, this is potentially less secure
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-04-11, rust version 1.34.0 (91856ed52 2019-04-10)
info: downloading component 'rustc'
 85.3 MiB /  85.3 MiB (100 %)   1.8 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 56.2 MiB /  56.2 MiB (100 %)   1.9 MiB/s ETA:   0 s 
info: downloading component 'cargo'
  4.3 MiB /   4.3 MiB (100 %)   1.9 MiB/s ETA:   0 s
info: downloading component 'rust-docs'
 10.2 MiB /  10.2 MiB (100 %)   1.5 MiB/s ETA:   0 s
info: installing component 'rustc'
 85.3 MiB /  85.3 MiB (100 %)  11.5 MiB/s ETA:   0 s
info: installing component 'rust-std'
 56.2 MiB /  56.2 MiB (100 %)  13.9 MiB/s ETA:   0 s
info: installing component 'cargo'
info: installing component 'rust-docs'
 10.2 MiB /  10.2 MiB (100 %)   2.6 MiB/s ETA:   0 s
info: default toolchain set to 'stable'

  stable installed - rustc 1.34.0 (91856ed52 2019-04-10)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
[root@424c5ff490c8 /]# 
```

**Comment by kinnison** [comment]
Thanks @victorjulien and once @cosmicexplorer 's tests finish, we'll just need confirmation for the cargo macos situation (though I *think* @cosmicexplorer you have at least one OSX 10.12 target in your suite -- will that try and run rustup ?)

**Comment by Eric-Arellano** [comment]
@kinnison for Pants, we do! Our macOS Rust shard uses Xcode 8.3 (macOS 10.12).

We're tracking the results at https://travis-ci.org/pantsbuild/pants/builds/524133299 (CI backlog right now). The shards we care about are
- all of the "Build Linux native engine" shards at the top, which run on Docker Centos6 and macOS 10.11
- some of the "Build wheels" shards, which also run on Docker Centos6 and macOS 10.11
- the two Rust test shards, which run on Ubuntu Xenial and macOS 10.12

FYI here's what our bootstrap code looks like after the experiment https://github.com/pantsbuild/pants/pull/7619/files.

**Comment by kinnison** [comment]
@Eric-Arellano Thanks for that clarification.  If all goes well and this merges, you can switch to fetching rustup-init.sh from the main rustup repo until I can get a release done to include the fix :-D

**Comment by alexcrichton** [comment]
> we'll just need confirmation for the cargo macos situation

FWIW we're just using Travis with the `xcode9.2` image, so not much special in Cargo. It seems like this would probably fix the issue there though.

**Comment by cosmicexplorer** [comment]
This seems to work for pants on Centos6: https://travis-ci.org/pantsbuild/pants/jobs/524133300 was failing before. The changes to consume it are in pantsbuild/pants#7619, so once this rustup PR lands we would edit our PR to consume the canonical version.

**Comment by kinnison** [comment]
Given all that, I'm inclined to hit merge :D

**Comment by kinnison** [comment]
@alexcrichton Do you want to promote the script to static.rlo on its own, or shall I prepare 1.18.1 tomorrow?

**Pull request merged**
