### PR TITLE
Download rust CI Docker images from a registry

### PR DESCRIPTION
**Pull request by Kobzol**
This PR changes the way rustup reuses the Docker images from `rust-lang/rust`. Instead of downloading layers from S3, it directly pushes the built images from a (ghcr.io) Docker registry.

The `rust-lang/rust` part of this change is [here](https://github.com/rust-lang/rust/pull/119290).

### CODE REVIEW

**Comment by Kobzol** [comment]
(Tests won't be green until https://github.com/rust-lang/rust/pull/119290 is merged).

**Comment by rbtcollins** [comment]
@Kobzol great, just let us know when to expect things to be working.

**Comment by rbtcollins** [comment]
I'm marking this as draft as its not expected to work yet.

**Comment by rami3l** [comment]
@Kobzol Looks like the blocking PR has been merged. I'll relaunch the CI checks and see if it works :)

Update: The CI is green, perfect! I'll perform the merge then.

**Review by rami3l — APPROVED** [review]

**Pull request merged**
