### PR TITLE
Show version of rust being installed

### LINKED ISSUE #1007: Please show me the version I'm downloading/updating
```
C:\Users\liigo>rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
 23.9 MiB /  28.8 MiB ( 83 %)  51.2 KiB/s ETA:  98 s
```

### PR DESCRIPTION
**Pull request by Diggsey**
Fixes #1007 

I haven't updated the tests yet in case we want to change how it's displayed.

### CODE REVIEW

**Comment by Diggsey** [comment]
Example output:
```
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2015-01-02, rust version 1.3.0
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'
```

**Comment by brson** [comment]
Patch looks good to me, but failures are legit. r=me when fixed.

**Pull request merged**
