### PR TITLE
Improve handling/reporting of keys

### PR DESCRIPTION
**Pull request by kinnison**
In order that we can see what keys we have access to and where
they came from, report the content of `cfg.get_pgp_keys()`.

@dignifiedquire is there an easier way to implement the key display code?  It'd be lovely if there were a clean way for `rpgp` to give me a nice render of the key algo+length+id among other things.  Or if fingerprints could be neatly formatted by the library.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Unfortunately there are no nice formatting tools in rpgp quite yet, but I'll take it as a feature request and try to get to it soonish.

**Comment by kinnison** [comment]
Okay, I'll try and add other bits and bobs to the PR tonight, and then I'll ask for a proper review.

**Comment by kinnison** [comment]
I recommend reading each commit in turn to ease review

**Review by dignifiedquire — APPROVED** [review]
nice

**Comment by kinnison** [comment]
Thank you for reviewing.

**Pull request merged**
