### PR TITLE
Reformat the entire codebase using `cargo fmt`

### PR DESCRIPTION
**Pull request by kinnison**
To make sure that people using editors which use rustfmt by default
on saving don't touch more lines than intended when working on the
rustup codebase, we'll take the hit to format it all once.

Please note, this depends on #1583 (as it effectively contains that commit also)

### CODE REVIEW

**Comment by nrc** [comment]
Did you do any manual fixups or is this all just running `cargo fmt`?

**Comment by kinnison** [comment]
@nrc The formatting commit was pure `cargo fmt` and no manual changes.

**Comment by kinnison** [comment]
All I did was rebase against current master and confirm there were no further formatting changes needed.

**Review by nrc — APPROVED** [review]
Thanks!

**Pull request merged**
