### PR TITLE
build: Try to cache cargo registry on Travis

### PR DESCRIPTION
**Pull request by tesuji**
I will often close and reopen to trigger rebuild after cache.

### CODE REVIEW

**Comment by kinnison** [comment]
There's little gain in caching the registry content AIUI but really we should look at what Travis recommend for this since I worked with them to make things as fast as we could a few weeks ago.

**Comment by tesuji** [comment]
The `cache: cargo` doesn't seem to work with `language: minimal`: https://travis-ci.com/rust-lang/rustup.rs/jobs/212050838

**Comment by kinnison** [comment]
Yeah, `cache: cargo` is probably only going to work for `langauge: rust` but you can see in travis' rust docs what it would cache so that you can replicate the behaviour for us.

**Comment by tesuji** [comment]
Apparently, time to cache ~/.rustup dir is longer than the time it saved
from download and install rust toolchain.

**Pull request closed without merging**
