### PR TITLE
Fix chrono deprecation warnings

### PR DESCRIPTION
**Pull request by ehuss**
A recent release of `chrono` introduced several deprecations of existing methods. This updates to use the undeprecated API.

### CODE REVIEW

**Review by rbtcollins — APPROVED** [review]
LGTM but I think we need to fix the centos image to make sure we won't have a break-fix on lint or some such. Feel free to merge earlier if this shows up as a failure in some other test, as we can roll-forward if needed.

**Comment by rbtcollins** [comment]
Could you rebase to get the centos check run against master's fix? Thanks!

**Comment by ehuss** [comment]
Done (although it looks like android is still failing).

**Comment by 0xPoe** [comment]
> (although it looks like android is still failing).

It's not related to your changes.

**Review by 0xPoe — APPROVED** [review]
Looks good to me. Could you please rebase your base branch to solve the conflicts?

**Comment by ehuss** [comment]
Sure, done.

**Comment by 0xPoe** [comment]
Thanks a lot!

**Pull request merged**
