### PR TITLE
Do all builds together in CI

### PR DESCRIPTION
**Pull request by rbtcollins**
This may help CI performance by reducing thrashing.

### CODE REVIEW

**Comment by rbtcollins** [comment]
Comparing times to https://github.com/rust-lang/rustup/pull/3223
(this vs base)
linux x86_64 38m v 34m
windows 42m v 46m
mac x64 51m v 49m
windows x86-gnu 52m v 60m
windows i686 52m v 55m

I suspect cross tenancy noise means these are variable anyway, but the key thing is that the slowest builds have gotten faster, so this should faster overall if that holds up; but if its just noise, we're no worse off.

We could also look at building-without-testing the unit tests on other platforms.

**Comment by rbtcollins** [comment]
Comparing times to https://github.com/rust-lang/rustup/pull/3223
(this vs base)
linux x86_64 38m v 34m
windows 42m v 46m
mac x64 51m v 49m
windows x86-gnu 52m v 60m
windows i686 52m v 55m

I suspect cross tenancy noise means these are variable anyway, but the key thing is that the slowest builds have gotten faster, so this should faster overall if that holds up; but if its just noise, we're no worse off.

We could also look at building-without-testing the unit tests on other platforms.

**Comment by rbtcollins** [comment]
Comparing times to https://github.com/rust-lang/rustup/pull/3223
(this vs base)
linux x86_64 38m v 34m
windows 42m v 46m
mac x64 51m v 49m
windows x86-gnu 52m v 60m
windows i686 52m v 55m

I suspect cross tenancy noise means these are variable anyway, but the key thing is that the slowest builds have gotten faster, so this should faster overall if that holds up; but if its just noise, we're no worse off.

We could also look at building-without-testing the unit tests on other platforms.

**Review by 0xPoe — APPROVED** [review]

**Comment by 0xPoe** [comment]
Thanks!

**Pull request merged**
