### PR TITLE
Remove needless map

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by kinnison** [comment]
The failure case showing here is fascinating -- Do you have any idea why it might be occurring?

**Comment by tesuji** [comment]
The test succeeded on second run: https://github.com/rust-lang/rustup/pull/2211/checks?check_run_id=402222296

**Comment by kinnison** [comment]
Yeah I saw that, but wondered what, if anything, might cause that.  It has exit code zero and yet failed the `.success()` check.  If you have no idea then I guess we put it down to a test bogon?

**Review by kinnison — APPROVED** [review]
The change is good.

**Comment by tesuji** [comment]
Sorry I have no ideas.

**Comment by kinnison** [comment]
@lzutao Fair enough, I'll keep an eye out.  Thanks for the patch.

**Pull request merged**
