### PR TITLE
add `force-non-host` flag to install subcommand

### PR DESCRIPTION
**Pull request by Emilgardis**
This touches on standing issue in https://github.com/cross-rs/cross/issues/536

ping https://github.com/cross-rs/cross/pull/554

### CODE REVIEW

**Comment by Emilgardis** [comment]
Has anyone been able to review this? The CI failure is unrelated.

**Comment by Emilgardis** [comment]
what's the status for this?

it's unexpected that `install` tells the user to use `--force-non-host`, but doesn't allow it in this context.

**Comment by kinnison** [comment]
So `rustup install` is a hidden semi-alias for `rustup toolchain install` which is the official installation command for toolchains.

It's unfortunate that so many people expected `rustup install` and so I was not permitted to remove it (or even cause it to emit information about how it's deprecated) because the way it's implemented causes this kind of problem for people with legacy use of the hidden alias.

I'm OK with adding this patch, but honestly I'd rather that `cross` also switched to the correct command form.

Could you please rebase this patch atop current master so that the CI hopefully shows clean?  I don't appear to be able to restart it.

**Comment by Emilgardis** [comment]
I'm fine with changing the command used in cross, but I think it makes sense to make this work as well.

rebased

**Comment by Emilgardis** [comment]
We actually already use `toolchain install` in the suggested change to use `--force-non-host`, but this pr doesn't touch that. Fixed that now :D

**Pull request merged**
