### PR TITLE
consistently add context with file path when parsing fails

### LINKED ISSUE #3851: all cargo commands error, because some manifest is broken
### Verification

- [X] I searched for recent similar issues at https://github.com/rust-lang/rustup/issues?q=is%3Aissue+is%3Aopen%2Cclosed and found no duplicates.
- [X] I am on the latest version of Rustup according to https://github.com/rust-lang/rustup/tags and am still able to reproduce my issue.

### Problem

Independent of the directory and command I run cargo errors with the following error message:
```
rustup show active-toolchain
error: error parsing manifest: TOML parse error at line 1478, column 23
     |
1478 | [[pkg.rust.target.aarcwin.extensions]]
     |                       ^
invalid table header
expected `.`, `]]`
```

```
 cargo --help
error: error parsing manifest: TOML parse error at line 1478, column 23
     |
1478 | [[pkg.rust.target.aarcwin.extensions]]
     |                       ^
invalid table header
expected `.`, `]]`
```
in vscode the rust-analyzer log is a bit more helpfull with:

```
rust-analyzer failed to load workspace: Failed to load the project at /home/bennet/git/project/Cargo.toml: Failed to query rust toolchain version at /home/bennet/git/project, is your toolchain setup correctly?: cd "/home/bennet/git/project" && "/home/bennet/.cargo/bin/cargo" "--version" failed, exit status: 1
stderr:
error: error parsing manifest: TOML parse error at line 1478, column 23
     |
1478 | [[pkg.rust.target.aarc<!--a bunch of nul bytes-->win.extensions]]
     |                       ^
invalid table header
expected `.`, `]]`
```
<details>
<summary>It shows a bunch of null bytes where `&lt!--a bunch of nul bytes-->` is.</summary>
image
</details>

This is under WSL2 Ubuntu on Windows 11, I believe the corruption might be due to a recent export import of the WSL Image/distribution.
But I think cargo should handle this better, at least a filename of the manifest that failed to parse would be good.

### Steps

1. somehow corrupt the manifest file
2. run any of the command show above

### Possible Solution(s)

Include manifest path in error message

### Notes

_No response_

### Rustup version

```console
$> rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```

### Installed toolchains

```console
$> rustup show  
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/bennet/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
esp

active toolchain
----------------

(error: error parsing manifest, TOML parse error at line 1478, column 23
     |
1478 | [[pkg.rust.target.aarcwin.extensions]]
     |                       ^
invalid table header
expected `.`, `]]`
)
```

### OS version

```console
WSL2 under Windows 11 with

$> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### PR DESCRIPTION
**Pull request by Skgland**
fixes #3851

### CODE REVIEW

**Comment by rami3l** [comment]
@Skgland Thanks for making this PR!

Would you mind explain in detail what is the motivation of this PR and what has been improved with a simple before/after comparison, for example?

PS: To make sure we are on the same page, regarding #3851 I would like to underline that the server incident causing bad manifests being downloaded is probably out of the scope of the Rustup project (so it possibly cannot be "fixed"), although improvements regarding error handling are welcomed.

**Comment by rami3l** [comment]
Your CI failure is https://github.com/rust-lang/rustup/issues/3852, we will be investigating this on our side.

**Comment by Skgland** [comment]
> Would you mind explain in detail what is the motivation of this PR and what has been improved with a simple before/after comparison, for example?
> 

Having a manifest parsing error while using cargo I initially assumed a mistake in the Cargo.toml,
though due to the problematic line in the error message that was quickly ruled out.
Next I tried to figure out where cargo was trying and failing to parse a manifest.
I assumed that this was maybe a manifest from the crates.io package registry cache, but searching for the line in `~/.cargo/` didn't bring up any results.
Only when I noticed rust-analyzer and `cargo --help` fail the same way did I come to the conclusion that the source is likely from the rustup wrapper of those binaries and not cargo itself and as such began searching in rustup.
This search could have been shorten had the manifest path been part of the error message, thus me not having to search for which file it was that had the error.

To recreate the error condition I inserted a NUL byte in a valid manifest file, resulting in the following error before/after my change.

Before: 

```
$> RUSTUP_HOME=home CARGO_HOME=home home/bin/cargo --help
error: error parsing manifest: TOML parse error at line 1286, column 24
     |
1286 | [[pkg.rust.target.aarch64-apple-darwin.components]]
     |                        ^
invalid table header
expected `.`, `]]`
```

After:

```
$> RUSTUP_HOME=home CARGO_HOME=home home/bin/cargo --help
error: could not parse manifest file: '/home/bennet/git/rustup/home/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/multirust-channel-manifest.toml': error parsing manifest: TOML parse error at line 1286, column 24
     |
1286 | [[pkg.rust.target.aarch64-apple-darwin.components]]
     |                        ^
invalid table header
expected `.`, `]]`
```

> PS: To make sure we are on the same page, regarding #3851 I would like to underline that the server incident causing bad manifests being downloaded is probably out of the scope of the Rustup project (so it possibly cannot be "fixed"), although improvements regarding error handling are welcomed.

Yes, I agree that the source of the manifest corruption is outside of rustup and as such out of scope. My goal with the Issue and this PR was to improve the error reporting. Also, I am pretty sure that there was no server incident involved, but I believe that the export and re-import of the WSL 2 distribution somehow corrupted the disk image file, resulting in the already installed manifest getting corrupted.

**Comment by rami3l** [comment]
@Skgland Thanks for the clarification!

At Rustup the word "manifest" is used specifically to refer to a certain kind of file downloaded from the Rustup release server, and, as you've found out, named `multirust-channel-manifest.toml`.

This file is specifically used to determine what are available in this channel, however I have no idea how you got that wrong (since we have shasum checks), sorry about that...

https://github.com/rust-lang/rustup/blob/3ba08da98221b2941aeb858e54cebc059859ffb7/tests/suite/cli_v2.rs#L280-L300

This PR might have to wait for #3852 before we get our merge CI green again. If you'd like, in the meantime, you can add a regression test in the file above.

**Review by rami3l — APPROVED** [review]

**Comment by Skgland** [comment]
Ok, just pushed a commit with a regression test

**Comment by Skgland** [comment]
Hm, looks like my regression test fails on windows due to `\` vs. `/` in the path in the error message.

**Comment by Skgland** [comment]
Do you have a suggestion for how to deal with the path-separator discrepancy on windows or should I skip the test on windows with e.g. `#[cfg(not(target_os = "windows"))]` the test?

**Comment by rami3l** [comment]
> Hm, looks like my regression test fails on windows due to `\` vs. `/` in the path in the error message.

@Skgland Just use /. It's a feature...

**Comment by rami3l** [comment]
> Do you have a suggestion for how to deal with the path-separator discrepancy on windows or should I skip the test on windows with e.g. `#[cfg(not(target_os = "windows"))]` the test?

@Skgland Please feel free to use what you consider appropriate for the problem. For example you can use two conditionally compiled assertions for Windows and Unix. Or you can compare the path components.

**Pull request merged**
