### PR TITLE
Remove error reporting from rustup-init.sh

### PR DESCRIPTION
**Pull request by noisegul**
In response to #987 I made rustup-init.sh terminate unsuccessfully instead of printing a message in case there is an error running rustup-init.exe.

### CODE REVIEW

**Comment by Diggsey** [comment]
Looks like `run()` is also used by `ignore()`, but I don't think the latter should exit if an error occurs.

**Comment by noisegul** [comment]
I see, so it would make more sense in this case to remove the conditional block completely in order to take out error reporting without influencing the behaviour of `ignore()`?

**Comment by Diggsey** [comment]
Yes, I think so.

**Comment by noisegul** [comment]
Thank you for your feedback. I changed this.

**Comment by lu-zero** [comment]
`run()` this way is basically a pass-through, it might make sense to not use it at all.

**Comment by noisegul** [comment]
I agree, in this case removing it would also re-establish the intended documentation factor of `ignore()`, as stated in the comments.

**Pull request merged**
