### PR TITLE
Detect and warn about x32

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Error message wrapped to eighty columns

### CODE REVIEW

**Comment by kinnison** [comment]
This change looks interesting, thank you for putting the effort in.

Can you suggest an easy way for me to install an x32 system in a VM so that I can test this?  Is there a distro you suggest for this?

**Comment by nabijaczleweli** [comment]
As far as a VM goes, I suggest following [this post](https://nabijaczleweli.xyz/content/blogn_t/001-x32-in-2020.html) for doing a x32 installation of Debian, which AFAIK is the only distribution that supports the ABI for the whole userland.

However, a chroot with a procfs mount should work just as well (but you'll need your host kernel to understand x32; if you're on Debian you'll need to boot with `syscall.x32=y`, if on Gentoo, it should Just Work with default config).

Something like
```
debootstrap --arch=x32 --variant=minbase --include=debian-ports-archive-keyring --no-check-gpg sid sid-x32/ https://deb.debian.org/debian-ports
mount --bind /proc/ sid-x32/proc/
chroot sid-x32/
```
should give you a bare-bones x32 userland.

(Technically all you need is an x32 `head(1)`, but that's more of a main in the arse than is worth.)

**Comment by kinnison** [comment]
I read through those instructions but don't feel comfortable messing around with debootstrap etc.  I'm fairly confident that this will work, having reread the shell so I'm going to merge this providing you can confirm you've tried the updated shell script on all of:

1. x86_64 with 64bit userland (should be entirely unaffected)
2. x86_64 with real 32bit userland (should be fine by your `else` clause)
3. x86_64 with x32 userland (I assume you've tested this already since otherwise you wouldn't have submitted the patch)

Are you able to confirm all of those are good with your change?  Sorry I can't get local testing set up but I'm in and out of Windows right now and don't have the time/space to do it.

**Comment by nabijaczleweli** [comment]
As far as I can tell, yes, all of those end up with the right cputype.

**Comment by kinnison** [comment]
Fantastic, thank you!

**Pull request merged**
