### PR TITLE
Use correct name for undefined linked toolchain invocation

### LINKED ISSUE #927: Incorrect error for undefined linked toolchain invocation
Here rust2 is not defined:

```
brian@ip-10-145-43-250:/mnt2/dev/s-structured-log-rs⟫ cargo +rust2 test
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```

I don't know why that error is emitted.

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #927.

### CODE REVIEW

**Comment by brson** [comment]
Thanks @topecongiro!

Can you add a test to `cli-exact.rs` that captures the output of of `cargo +bogus test` after this? You should be able to crib off the existing cases in that file.

**Comment by topecongiro** [comment]
@brson I will try and rebase. Thank you!

**Comment by brson** [comment]
Interesting failure here @topecongiro on windows. It looks to me like it's failing because on windows rustup is emitting a "info: found 0 remaining processes" .... which is bizarre. I think you should just delete that `info!` line from `job.rs` to make all platforms agree.

**Comment by topecongiro** [comment]
@brson Thank you for pointing out! Rebased.

**Pull request merged**
