### PR TITLE
Add PATH in post-install message when not modifying PATH

### LINKED ISSUE #374: post-install message when not modifying PATH should include the path
> I purposfully asked rustup not to modify my PATH envvar. At the end of the install I got this helpful reminder:

```
To get started you need Cargo's bin directory in your `PATH`
environment variable.
```

> It would be even more helpful if it also reminded me what bin directory to add :grin:

[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/101?u=brson).

### PR DESCRIPTION
**Pull request by f-bro**
Fixes #374 

Unix:
```
To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable.
```

Windows:
```
To get started you need Cargo's bin directory (C:\Users\f-bro\.cargo\bin) in
your PATH environment variable. This has not been done automatically.
```

### CODE REVIEW

**Comment by Diggsey** [comment]
Thanks for the PR!

I think it would be good to unify some of the logic here, across windows and linux:
- Give `canonical_cargo_home` logic for both windows and non-windows.
- Switch to using `canonical_cargo_home()` on all platforms
- Add the bin path to the `post_install_msg_win` as well (it's currently missed)

**Comment by f-bro** [comment]
Yes, it would be more consistent.
I will have a look tomorrow.

**Comment by f-bro** [comment]
It looks like AppVeyor couldn't download rust-std:
```
Downloading rustup-init.exe (7,601,125 bytes)...100%
rustup-init.exe -y --default-toolchain=nightly-2017-04-25-x86_64-pc-windows-msvc
info: syncing channel updates for 'nightly-2017-04-25-x86_64-pc-windows-msvc'
info: downloading component 'rustc'
info: downloading component 'rust-std'
```
The console output stops here.

**Comment by Diggsey** [comment]
Probably just a network failure.

LGTM, except `HOMEPATH` should be `USERPROFILE`, (I just fixed that in the online editor)

@bors r+

**Pull request merged**
