### PR TITLE
Minor clean up and fix some clippy warnings

### PR DESCRIPTION
**Pull request by tesuji**
r? @kinnison

### CODE REVIEW

**Review by kinnison — CHANGES_REQUESTED** [review]
Thanks, this looks to be a lot of useful cleanups; however the `rustfmt` patch in the middle makes me very sad.  Could you please go through the rebase and fold the formatting into the requisite fix patches instead?

**Comment by lzutao** [comment]
Done.

**Comment by tesuji** [comment]
Done.

**Review by kinnison — COMMENTED** [review]
This looks good to me.

However before I merge - in a lot of places we have std::foo::stuff where that is (I thought) part of the prelude.  (e.g. `std::result::Result::ok` rather than `Result::ok`) - is the fully qualified path needed?

I won't block merge on changing them if not, but I would like to know.

**Comment by tesuji** [comment]
Because we have shadowed origin Result with Result from `error-chain`.

Edit: Also I got this error:
```rust
error[E0631]: type mismatch in function arguments
   --> src/cli/common.rs:103:10
    |
103 |         .and_then(Result::ok)
    |          ^^^^^^^^
    |          |
    |          expected signature of `fn(std::result::Result<std::string::String, std::io::Error>) -> _`
    |          found signature of `fn(std::result::Result<_, errors::Error>) -> _`

```

**Review by kinnison — APPROVED** [review]

**Pull request merged**
