### PR TITLE
Purge Fastly cache after release

### PR DESCRIPTION
**Pull request by jdno**
When releasing a new version of rustup, we need to purge the cached version on Fastly. This is done by calling Fastly's API using curl and purging the surrogate key that is used for rustup.

See https://github.com/rust-lang/simpleinfra/issues/415 for more details.

### CODE REVIEW

**Comment by rami3l** [comment]
@jdno Thank you! Since this commit cannot be tested (and is essentially used by t-infra exclusively), I entrust you with its correctness.

**Review by rami3l — APPROVED** [review]

**Comment by rami3l** [comment]
@jdno One (newbie) question: is it possible to move this script to e.g. some repo that you directly control? After all, it's a bit weird to have something in our repo that we can't run 🤔

**Comment by jdno** [comment]
Thanks for the quick review! I'll ask @Mark-Simulacrum to have a look as well.

Before we merge this it would be great to test it with `dev-static`. I've tested the snippets that I've added and am fairly confident that everything should just work™. But it'd be great to actually confirm this. 🙈

**Comment by jdno** [comment]
> @jdno One (newbie) question: is it possible to move this script to e.g. some repo that you directly control? After all, it's a bit weird to have something in our repo that we can't run 🤔

Mark and I briefly [discussed in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Purge.20Fastly.20after.20rustup.20releases) that it would be good to replace this script with an automated release process, maybe similar to [rust-lang/promote-release](https://github.com/rust-lang/promote-release) which runs on AWS CodeBuild and is deployed through [rust-lang/simpleinfra](https://github.com/rust-lang/simpleinfra/blob/master/terraform/releases/impl/promote-release.tf).

We can definitely have a more concrete discussion about how the release process can be automated/improved. 🙂

**Comment by djc** [comment]
Agreed with @rami3l that it doesn't make much sense for us to review this. A more automated release process sounds good, I guess that's something someone from the infra team would implement?

**Comment by rami3l** [comment]
This is waiting for @Mark-Simulacrum's approval then.

**Comment by jdno** [comment]
We've been discussing refactoring the release process [in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rustup.20releases.20as.20part.20of.20promote-release) and on the draft implementation [in promote-release](https://github.com/rust-lang/promote-release/pull/84).

The outcome of that discussion is that we definitely want to reimplement the Python script as part of `promote-release`. But that requires some modifications to the current release process.

I've written a draft for that process in #3844.

**Pull request closed without merging**
