### PR TITLE
Clearer detecting 64-bit Linux with 32-bit userland on mips64el

### PR DESCRIPTION
**Pull request by tesuji**
r? @kinnison

### CODE REVIEW

**Comment by kinnison** [comment]
I'm fairly sure this looks OK, but I want to wait until we have some CI for the `rustup-init.sh` file before I consider approving.

**Comment by tesuji** [comment]
I manually tested this PR on mips, mipsel and mips64el linux target. `rustup-init.sh` ran OK but `rustup-init` didn't, mostly because of required *glibc* version too high (2.26).

**Comment by kinnison** [comment]
OK, that's good, but my point stands that I'm wary of merging further changes to rustup-init.sh until we have some CI in place for it.

**Comment by tesuji** [comment]
Rebased on master.

**Review by kinnison — APPROVED** [review]
We now have shellcheck at least for the install shell script

**Pull request merged**
