### PR TITLE
Add --toolchain option to 'rustup doc'

### LINKED ISSUE #1477: Allow specifying rustup doc toolchain
As discussed in https://github.com/rust-lang/rust/issues/53158. If we would like to open the nightly docs with stable as default toolchain. We need to:

```
$ rustup default nightly
$ rustup doc --std
$ rustup default stable
```

As well, part of my confusions is that I thought the following works.

- `rustup +nightly doc` (cargo uses this so I thought it applies to rustup)
- `rustup doc --toolchain=nightly` (`rustup component add clippy preview --toolchain=nightly` works though)

~~Or maybe there's a quick way to switch between stable and nightly docs if both toolchains are installed?~~ Answered in https://github.com/rust-lang/rust/issues/53158#issuecomment-411291134 by @cuviper

### PR DESCRIPTION
**Pull request by pickfire**
Fix #1477

### CODE REVIEW

**Review by nrc — COMMENTED** [review]
This looks good, but could you add a test please?

**Comment by pickfire** [comment]
@nrc I am not sure where can I add tests for this. I checked but the shorthand is handled by somewhere else so should we even add tests for this?

**Comment by pickfire** [comment]
Added tests with simple check to test if toolchain is working with nightly.

**Comment by nrc** [comment]
Great, thank you

**Pull request merged**
