### PR TITLE
show active-toolchain with rustc info

### LINKED ISSUE #2685: rustup show active-toolchain could be more detailed
Right now `rustup show active-toolchain` shows this on my system:
````
nightly-x86_64-unknown-linux-gnu (default)
````

It would be nice to not only know the active channel but perhaps also show the actual compiler version and the corresponding hash? (perhaps through a `--verbose` flag?)
````
nightly-x86_64-unknown-linux-gnu (default) - 1.52.0-nightly (94736c434 2021-02-27)
````

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rustup/issues/2685

### CODE REVIEW

**Comment by 0xPoe** [comment]
cc:  @kinnison 

Could you please take a look?

**Comment by 0xPoe** [comment]
@kinnison Ping~

If I disturb you, please let me know. I will stop pinging you and wait for your review.

**Comment by kinnison** [comment]
Could you please add a comment here showing what a **full** output of `rustup show` displays (before/after your PR if it has changed) and what `rustup show --verbose` shows?

I'm not entirely sure it's worth adding `--verbose` rather than just always showing the information so I'd like to see.

**Comment by 0xPoe** [comment]
Without my change:
```sh
stable-x86_64-apple-darwin (default)
```

with my change but without verbose:
```sh
➜  rustup git:(rustin-patch-show) ./home/bin/rustup  show active-toolchain                                     
stable-x86_64-apple-darwin (default)
➜  rustup git:(rustin-patch-show) 
```

with my change and verbose:
```sh
➜  rustup git:(rustin-patch-show) ./home/bin/rustup  show active-toolchain --verbose
stable-x86_64-apple-darwin (default) - rustc 1.51.0 (2fd73fabe 2021-03-23)
➜  rustup git:(rustin-patch-show) 
```

**Comment by 0xPoe** [comment]
@kinnison ping~

**Comment by rbtcollins** [comment]
I think showing it in the same format that `rustup show` does would be better: one per line. Concretely this is better for folk using sed to query etc.

**Comment by 0xPoe** [comment]
> I think showing it in the same format that `rustup show` does would be better: one per line. Concretely this is better for folk using sed to query etc.

Fixed.

**Review by kinnison — APPROVED** [review]

**Pull request merged**
