### PR TITLE
Separate release jobs

### PR DESCRIPTION
**Pull request by rbtcollins**
This is layered on the hardlink PR; it hopefully makes things even faster by only building whats needed in release mode.

### CODE REVIEW

**Comment by rbtcollins** [comment]
(Note for assessing performance - this resets the cache keys for everything, so a re-run will be needed to really tell.

**Comment by rbtcollins** [comment]
@hi-rustin this too is ready for review

**Review by 0xPoe — COMMENTED** [review]
Does this mean we don't run any windows tests on PR?

**Comment by rbtcollins** [comment]
Hmm, my intent was certainly to run windows tests. Lets me see whats happening.

**Comment by rbtcollins** [comment]
https://github.com/rust-lang/rustup/actions/runs/4311356314 is the problem

**Comment by rbtcollins** [comment]
(And fixed).

@hi-rustin  I'm going to merge this - its a substantial win - if you have any further comments let me know and I'll fix them up

**Pull request merged**
