### PR TITLE
Fix broken aarch64-unknown-linux-gnu GitHub Actions

### PR DESCRIPTION
**Pull request by 0xPoe**
I found that rustup master CI keeps failing. https://github.com/rust-lang/rustup/actions/runs/3197393101/jobs/5220541587
This cause by https://github.com/rust-lang/rust/commit/d0142ce27a31fd1da9f2bf4b295840e3a969d295#diff-38eddf433d93f44424b7c45d25a2984569af2a2d4eebfe47b7c9e2492dddf9b4
We have to update it.

### CODE REVIEW

**Comment by 0xPoe** [comment]
I think I fixed aarch64-unknown-linux-gnu GitHub Actions, please check out https://github.com/rust-lang/rustup/actions/runs/3216435162/jobs/5258322908.

arrch64-linux-android failed caused by https://github.com/rust-lang/rust/pull/102332#issuecomment-1272730482.

**Comment by 0xPoe** [comment]
I am going to drop [this commit](https://github.com/rust-lang/rustup/pull/3082/commits/48067e5113ee207dc265ea41c198719dd5ca37a8) because we wanna skip the aarch64-unknown-linux-gnu GitHub Action on PR.

**Review by rbtcollins — APPROVED** [review]
LGTM

**Comment by 0xPoe** [comment]
Thanks for your review!  💚 💙 💜 💛 ❤️

**Pull request merged**
