### PR TITLE
Add/remove multiple components+targets

### PR DESCRIPTION
**Pull request by durka**
Same as #986 but for components and targets. After this I don't see any more places to add `.multiple(true)`.

cc #1005

### CODE REVIEW

**Comment by durka** [comment]
Not sure what's going on with `multi_host_smoke_test` but I can reproduce locally, will figure it out.

**Comment by durka** [comment]
Another note is that all these loops exit on the first error. If you `rustup component add x y` and `x` doesn't exist (or is already installed, see #1009), it won't get to `y`. I'm not sure whether this is desired behavior.

**Comment by brson** [comment]
> Another note is that all these loops exit on the first error. If you rustup component add x y and x doesn't exist (or is already installed, see #1009), it won't get to y. I'm not sure whether this is desired behavior.

Seems ok for now when there are no dependencies between components that need to be maintained.

**Comment by durka** [comment]
Should be fixed now. Not really sure what I'm doing in the mock manifest code.

**Pull request merged**
