### PR TITLE
Document automatic installation behavior via `rustup show`

### LINKED ISSUE #2639: Document autoinstallation behaviour on overrides page of docs
In some cases it can confuse a small but not insignificant number of people that the override files can cause autoinstallation of toolchains, and in other cases people are not sure *what* command to use to trigger this activity best.

We should document the autoinstallation behaviour as part of https://rust-lang.github.io/rustup/overrides.html and we should make recommendations about the "best" way to trigger it, for example so that CI providers can implement it.

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rustup/issues/2639

### CODE REVIEW

**Comment by rbtcollins** [comment]
I'm torn on this - I haven't even read the patch yet, but see https://github.com/rust-lang/rustup/issues/2686 and https://github.com/rust-lang/rustup/issues/1397

This patch is documenting things we consider bugs. It is good to have the current behaviour documented, OTOH then folk may remember what they read and not-re-read the docs after we fix those bugs. perhaps a note to the effect that this is under review or something, and a link to the bugs?

**Comment by 0xPoe** [comment]
> perhaps a note to the effect that this is under review or something, and a link to the bugs?

Add a note for it. Thanks for the review, I didn't notice that it was considered a bug. 🤣

**Comment by 0xPoe** [comment]
Also, I'm not sure that if it's considered a bug, then we should still document it. Because @kinnison his original idea was to let people know about the behavior and use it in CI. But if it is a bug, will it have a big impact on users when it is fixed?

**Comment by rbtcollins** [comment]
yeah, CI users will use 'rustup ensure' or whatever verb we end up on.'

**Comment by 0xPoe** [comment]
@rbtcollins @kinnison Should I close the PR or is this clarification acceptable for now? (I don't currently recommend it in the description for use in CI)

**Pull request merged**
