### PR TITLE
 Fallbacks to wget if curl not installed

### PR DESCRIPTION
**Pull request by t-botz**
Tested in ubuntu docker with 
 1. Both curl and wget installed
 2. only wget installed
 3. only curl installed

Console output for wget looks like this :
```shell
root@845dcc4ba103:/# wget -qO- https://raw.githubusercontent.com/thibaultdelor/rustup.rs/faa08bd786b7282500cc4162a2f428484c891130/rustup-init.sh | sh
info: downloading installer
--2018-03-08 06:54:27--  https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
Resolving static.rust-lang.org (static.rust-lang.org)... 54.230.135.47, 54.230.135.132, 54.230.135.130, ...
Connecting to static.rust-lang.org (static.rust-lang.org)|54.230.135.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12984456 (12M) [application/x-sharedlib]
Saving to: '/tmp/tmp.DQhaNqhC4q/rustup-init'

/tmp/tmp.DQhaNqhC4q/rustu 100%[==================================>]  12.38M  11.0MB/s    in 1.1s    

2018-03-08 06:54:29 (11.0 MB/s) - '/tmp/tmp.DQhaNqhC4q/rustup-init' saved [12984456/12984456]


Welcome to Rust!

This will download and install the official compiler for the Rust programming 
language, and its package manager, Cargo.

It will add the cargo, rustc, rustup and other commands to Cargo's bin 
directory, located at:

  /root/.cargo/bin

This path will then be added to your PATH environment variable by modifying the
profile file located at:

  /root/.profile

You can uninstall at any time with rustup self uninstall and these changes will
be reverted.

Current installation options:

   default host triple: x86_64-unknown-linux-gnu
     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation

```

### CODE REVIEW

**Comment by t-botz** [comment]
@TitanSnow I slightly modified your version to avoid duplication of `command -v`. That way we are sure to be consistent on how we test existence of a command but also we might want to not use it because [-v|-V is not POSIX 2004 compliant](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835498).

r? @alexcrichton @nrc

**Comment by t-botz** [comment]
If approved, should close https://github.com/rust-lang-nursery/rustup.rs/pull/1346 and https://github.com/rust-lang-nursery/rustup.rs/pull/1268

**Comment by ghost** [comment]
Looks good :smile:

**Comment by nrc** [comment]
Looks good to me. r? @alexcrichton

**Pull request merged**
