### PR TITLE
Switch to std::fs::read_to_string

### PR DESCRIPTION
**Pull request by tesuji**
According to [the doc][1]:  it is generally faster than reading into a string created with `String::new()`.

[1]: https://doc.rust-lang.org/nightly/std/fs/fn.read_to_string.html

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
While I question the wisdom of needing to improve performance on any of these pathways, I do agree that it simplifies the codebase by removing two implementations of what is essentially something from `std`

**Comment by kinnison** [comment]
I *think* the test failures are windows being odd.  But I'd like @rbtcollins to confirm before merging.

**Review by rbtcollins — APPROVED** [review]
LGTM

**Comment by rbtcollins** [comment]
The CI failures I haven't investigated, but I see no platform interactions to be concerned about.

**Pull request merged**
