### PR TITLE
Remove MSI

### PR DESCRIPTION
**Pull request by ghost**
This PR removes the `rustup-win-installer` directory, as suggested in #1611.

### CODE REVIEW

**Comment by dwijnand** [comment]
Looks like rustup's CI is broken with https://github.com/rust-lang/cargo/pull/6192.  Need to declare 'download' as a workspace member.

**Comment by ghost** [comment]
Thank you @dwijnand, for pointing me in the right direction.

**Review by dwijnand — APPROVED** [review]
Thanks!

**Comment by nrc** [comment]
@alexcrichton are we using this MSI code at all?

@emanuelbutacu could you rebase please?

**Comment by dwijnand** [comment]
I also found out that, literally, the most commented issue in the issue tracker is "Add windows gui / msi installer" https://github.com/rust-lang/rustup.rs/issues/253

So maybe we _shouldn't_ remove this?  (I'm just asking, I'm happy to remove it.)

**Comment by ghost** [comment]
In that case, we should wait for more people to chime in. I'll hold on to rebase until after we come to an agreement. How does that sound?

**Comment by alexcrichton** [comment]
Looks like y'all may have found this, but the msi installer I believe is not currently used at all, but was in development historically to become the primary installation method on Windows. I'm not personally aware of what are the remaining blockers of it.

**Comment by kinnison** [comment]
My gut feeling is that if we have no Windows-savvy developers on the WG right now, then removing it is the most sensible option.  We can always retrieve it from git later, but for now it's just in the way and will be a bogon as @dwijnand goes about his restructuring of the codebase which we'd like to do after 1.17.0

**Comment by ghost** [comment]
I don't think the failing test has anything to do with this PR, though, I might be wrong. Can someone else confirm this?

**Comment by kinnison** [comment]
Well, that's an interesting test failure.

**Comment by dwijnand** [comment]
Failure

```
failures:
---- rustup_stable_no_change stdout ----
running "/src/target/x86_64-unknown-linux-gnu/tests/rustup-exe.S9E4LlGpUVkM/rustup" "set" "default-host" "x86_64-unknown-linux-gnu"
status: exit code: 0
----- stdout
----- stderr
running "/src/target/x86_64-unknown-linux-gnu/tests/rustup-exe.S9E4LlGpUVkM/rustup" "update" "stable" "--no-self-update"
status: exit code: 0
----- stdout
  stable-x86_64-unknown-linux-gnu installed - 1.0.0 (hash-s-1)
----- stderr
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2015-01-01, rust version 1.0.0
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-docs'
running "/src/target/x86_64-unknown-linux-gnu/tests/rustup-exe.S9E4LlGpUVkM/rustup" "update" "--no-self-update"
status: signal: 11
----- stdout
----- stderr
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
> rustup update --no-self-update
out.ok: false
out.stdout (1 lines):
    
    
out.stderr (1 lines):
    info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    
expected.ok: true
expected.stdout (3 lines):
    
      stable-x86_64-unknown-linux-gnu unchanged - 1.0.0 (hash-s-1)
    
    
expected.stderr (1 lines):
    info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    
[src/rustup-mock/src/clitools.rs:228] out.stdout == stdout = false
[src/rustup-mock/src/clitools.rs:229] out.stderr == stderr = true
thread 'rustup_stable_no_change' panicked at 'explicit panic', src/rustup-mock/src/clitools.rs:230:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    rustup_stable_no_change
test result: FAILED. 57 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out
```

I'll restart the build.

**Pull request merged**
