### PR TITLE
ci: Set up cache build with sccache

### PR DESCRIPTION
**Pull request by tesuji**
~Blocked on #1815.~

Now the first build time is a little slower, but incremental builds
in the same branch should be faster.

r? @kinnison

### CODE REVIEW

**Comment by kinnison** [comment]
When you say it's a little slower on first build of a branch -- how much slower are we talking?
How many builds does it take to get that slowness back?  Is it on the second build, the third?

**Comment by tesuji** [comment]
Look at build time on Travis, this PR may take about 30 seconds more than
normal builds. The second build and later should be faster ([upto 4 minutes][1]).

[1]: https://travis-ci.com/rust-lang/rustup.rs/builds/110499868

**Comment by kinnison** [comment]
Does the rustc docker contain sccache then?  I couldn't see how it turned up otherwise.

**Comment by tesuji** [comment]
Yes. In [this line][1] from build log, sccache is called.

[1]: https://travis-ci.com/rust-lang/rustup.rs/jobs/197478512#L490

**Pull request merged**
