### PR TITLE
Enable loongarch64-linux-gnu builds on stable

### PR DESCRIPTION
**Pull request by heiher**
Enable loongarch64-linux-gnu builds on stable and request a new release.

### CODE REVIEW

**Comment by 0xPoe** [comment]
@heiher Did you try it on your repo? Does it work? You could trigger it on your repo's GitHub Actions and see what is happening.

**Comment by heiher** [comment]
Yeah. It works: https://github.com/loongarch-rs/rustup/actions/runs/5544845402

**Comment by heiher** [comment]
Rebased, CI results: https://github.com/loongarch-rs/rustup/actions/runs/5609694321 (loongarch64 build success)

**Comment by heiher** [comment]
@hi-rustin Could you please review it again? Thanks.

**Comment by heiher** [comment]
Hello, @rbtcollins Could you please review this PR? Thanks.

**Pull request merged**
