### PR TITLE
Make use of rustc docker images on other targets (except android)

### PR DESCRIPTION
**Pull request by tesuji**
r? @kinnison 

**Note:** Please merge only after commenting out the build condition in `.travis.yml`: 
```yml
      # if: branch != master
```

### CODE REVIEW

**Comment by kinnison** [comment]
The android builds fail with link errors you might need to look deeper into

**Comment by tesuji** [comment]
The build looks good: https://travis-ci.com/rust-lang/rustup.rs/builds/112859834 .
I will remove the WIP commit before merging.

**Comment by kinnison** [comment]
Yep, looks good, please drop the WIP commit

**Comment by tesuji** [comment]
I dropped the WIP commit.

**Review by kinnison — APPROVED** [review]
LGTM

**Pull request merged**
