### PR TITLE
fix feature-hidden clippy warnings (clippy::len_zero)

### PR DESCRIPTION
**Pull request by matthiaskrgr**
found with cargo clippy .. --all-features

### CODE REVIEW

**Comment by rbtcollins** [comment]
Thank you. I think there are some in the optional curl downloader as well, but I haven't managed to replicate that locally yet for some reason. I'll merge this when it passes CI.

**Comment by rbtcollins** [comment]
Ah, we need to add --all

**Comment by matthiaskrgr** [comment]
Hm,I checked with `--all-targets --all-features` and this was all I found :D

**Comment by rbtcollins** [comment]
yeah, `cargo +nightly clippy --all --all-targets --all-features -- -D warnings` is the full thing; --all-features will be tricky for Windows developers as installing OS libraries can be fiddly compared to the ease of apt install libcurl-dev etc.

**Comment by rbtcollins** [comment]
https://github.com/rust-lang/rustup/pull/2460 follows this up with additional coverage

**Pull request merged**
