### PR TITLE
Fix lint

### PR DESCRIPTION
**Pull request by rbtcollins**

### CODE REVIEW

**Review by 0xPoe — APPROVED** [review]
While rustfmt doesn't complain, I think it's a better format.

Looks good to me.

**Comment by rbtcollins** [comment]
@hi-rustin rustfmt does complain, thats how I found this lint.

**Comment by 0xPoe** [comment]
> @hi-rustin rustfmt does complain, thats how I found this lint.

My rustfmt does not complain.

➜  rustup git:(master) cargo fmt --version
rustfmt 1.4.37-nightly (0bd2b192 2021-04-03)

**Comment by rbtcollins** [comment]
Yes, because the code isn't being compiled on your machine. Look at the cfg macro surrounding it.

**Comment by 0xPoe** [comment]
> Yes, because the code isn't being compiled on your machine. Look at the cfg macro surrounding it.

Got it, sorry I missed this cfg macro.

**Pull request merged**
