### PR TITLE
Refine suggestions of sourcing `$HOME/.cargo/env`

### LINKED ISSUE #3415: rustup suggest executing "source ...", but this command is absent in dash
### Problem

Command `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` in the end suggest running command `source "$HOME/.cargo/env"`. But there is no command `source` in dash (this is Debian's default shell). So, please fix your suggestion to `.` instead of `source`.

I copied this `source "$HOME/.cargo/env"` from rustup output and pasted to my dockerfile. And docker build failed, because of this problem

### Steps

.

### Possible Solution(s)

_No response_

### Notes

_No response_

### Rustup version

```console
.
```

### Installed toolchains

```console
.
```

### PR DESCRIPTION
**Pull request by rami3l**
Closes #3415.

### CODE REVIEW

**Review by djc — APPROVED** [review]
Drive-by review: nice!

**Comment by rami3l** [comment]
@rbtcollins The CI check failed spuriously and requires a rerun.

**Comment by rami3l** [comment]
Weird. After a rerun I'm still getting errors that should have nothing to do with my changes...

**Comment by djc** [comment]
The armv7-linux issues are an upstream problem: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rustup.20CI.20fails.20to.20install.20Docker.20images.20for.20armv7-linux. macOS seems to be suffering from intermittent issues in different tests. I think we should just merge this despite the CI failures.

**Pull request merged**
