### PR TITLE
Add armv8l support

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes https://github.com/rust-lang-nursery/rustup.rs/issues/1055

### CODE REVIEW

**Comment by malbarbo** [comment]
Should `src/rustup-dist/src/dist.rs` be updated? It seems that it does not contains the same cases of `rustup-init.sh`.

**Comment by ghost** [comment]
*In Emperor Palatine accent* DEW IT

**Comment by Diggsey** [comment]
Thanks! Yes I think you'll probably need to add it here too: https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-dist/src/dist.rs#L165

**Comment by malbarbo** [comment]
Done. I also add a missing armv7l case.

**Pull request merged**
