### PR TITLE
Chunked disk IO

### PR DESCRIPTION
**Pull request by rbtcollins**
Just some cleanups at this stage.

### CODE REVIEW

**Comment by kinnison** [comment]
These cleanups look good - are you intending to take this further or is it blocked on effective-limits updates or somesuch?

**Comment by rbtcollins** [comment]
I intend to take it further but we can of course land it incrementally if
you like

**Comment by kinnison** [comment]
Have you been able to verify the freebsd and netbsd builds?  If so, then I suggest relabelling the PR and landing the cleanups since they add support for effective-limits in those platforms.

**Comment by rbtcollins** [comment]
I have not - who would be a good person to ask to do that?

**Comment by kinnison** [comment]
Having built them, I'm not sure other than using a VM or somesuch.  Perhaps if you can build them you could ask on the internals.rust-lang.org forum for a tester?  Or reddit?

**Comment by rbtcollins** [comment]
To be clear; this doesn't add effective-limits supports on those platforms - it just moves the handling of the lack of support into effective-limits - and goes *some way* to adding support via the related PRs on libc etc.

I would like to just merge this I think and ask for testers after its in master - since passing CI on the relevant platforms in effective-limits itself.

**Comment by kinnison** [comment]
You have a Cargo.lock conflict but I remain positive on merging this otherwise.

**Review by kinnison — APPROVED** [review]

**Comment by kinnison** [comment]
Good to merge on green

**Pull request merged**
