### PR TITLE
Additional sudo checks

### PR DESCRIPTION
**Pull request by das-sein**
An attempt to improve sudo warning sensitivity to help avoid issues like #1911 

Introduces two additional checks.

The first checks for sudo-specific environment variables, then triggers an error message like the home directory discrepancy test which requires explicit user interaction to override.

The second attempts to detect a discrepancy between the actual and effective IDs of the user executing the process, which triggers a warning message that alerts the user they may be executing the installation binary as sudo. This requires no user interaction to bypass.

### CODE REVIEW

**Review by kinnison — COMMENTED** [review]
This looks like it ought to be good, but I wonder if we might want a test for at least the environment one?

**Comment by das-sein** [comment]
@kinnison I think you're right. The test cases might be a bit tricky to create, but it would be good to increase coverage as I don't think this function is presently tested at all.

**Comment by kinnison** [comment]
Hi @fotocoyotl 

Have you had any further thoughts around adding a test case for this?  Setting specific environment variables before running a test of `rustup-init` ought not to be too hard.

Also, could you rebase onto current master as I've merged a CI fix to try and mitigate the windows test failures.

**Comment by das-sein** [comment]
@kinnison I have, just haven't had a chance to implement them yet, sorry. Rebased.

**Comment by kinnison** [comment]
Hi @latrare 

Happy new year!  I was wondering if you might have time in this new year to pick up this work and complete the remaining testing needed to make it mergeable?  If you simply don't have the time/energy/interest then that's completely fine, but if you could let us know either way, I'd appreciate it.

Thanks again for all your efforts last year with Rustup.

Daniel.

**Pull request closed without merging**
