### PR TITLE
Bring rustup.js and markup into alingment with rust-www

### PR DESCRIPTION
**Pull request by brson**
This makes rustup.js the same as on rust-www, pulls in
some of the language from rust-www, pulls in some fixes
to platform detection, fixes some css.

### CODE REVIEW

**Comment by brson** [comment]
This needs to be reviewed and merged with https://github.com/rust-lang/rust-www/pull/1128.

**Comment by Diggsey** [comment]
LGTM, but maybe we should just remove `rustup.js` from one of these repos and have it link to `rustup.js` from the other?

**Comment by brson** [comment]
@Diggsey seems ok to me, except for risk of possible unanticipated drift between the two.

**Comment by brson** [comment]
I'm not inclined to work on this further, but doing the change @Diggsey suggested sounds fine.

**Pull request merged**
