### PR TITLE
correctly uninstall toolchains that are stale symlinks

### LINKED ISSUE #1169: Cannot remove linked toolchain
I added a toolchain via `rustup toolchain link myrust <path>` that I now want to remove. However, `rustup toolchain uninstall myrust` says `info: no toolchain installed for 'myrust'`. It seems that either it is impossible to uninstall ("unlink") a linked toolchain, or at least that feature it so well hidden that it is very hard to find.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes #1169

I'd like to add a test for this -- what is the best way to do that?

### CODE REVIEW

**Comment by RalfJung** [comment]
I found a way to test this. Now I guess I will see whether this also works on Windows...

**Comment by RalfJung** [comment]
I'm happy to rebase, but I'd appreciate to get some form of feedback on whether this approach is even going to get accepted.

**Comment by alexcrichton** [comment]
The fix looks good to me, sorry for the delay here! I'll r+ if you'd like to rebase

**Comment by RalfJung** [comment]
Great :)
Rebase done and (force-)pushed into this PR.

**Pull request merged**
