### PR TITLE
feature: include self-update status in check

### LINKED ISSUE #2577: Include rustup self-update status in `rustup check`
**Describe the problem you are trying to solve**
When checking whether toolchain updates are available it would be useful to see that there is also a rustup update available.

**Describe the solution you'd like**
Include rustup's own version status in the output of `rustup check`

**Notes**

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rustup/issues/2577

### CODE REVIEW

**Comment by hi-rustin** [comment]
@Nemo157 @kinnison  I think maybe we should support "rustup self check" instead of just including the status in the "rustup check" result.

**Comment by 0xPoe** [comment]
@kinnison Could you please take look?  Thanks!

**Comment by kinnison** [comment]
This looks pretty good.  I'm not in a position to test this out today, but will endeavour to do so in the next few days.

**Review by kinnison — CHANGES_REQUESTED** [review]
In general I like this, though I think it'd be slightly better if `rustup check` contained a line for rustup in the case of there being no update.  e.g.

`rustup - Up to date : 1.23.1`

Also, could you clean up your commit message when you're done?  Currently it feels like you made some number of commits, then squashed them together without cleaning it up.

This is very close to being mergeable.

**Comment by 0xPoe** [comment]
> In general I like this, though I think it'd be slightly better if `rustup check` contained a line for rustup in the case of there being no update. e.g.

Added.

**Comment by 0xPoe** [comment]
Thanks for your review! ❤️  @kinnison

**Review by kinnison — CHANGES_REQUESTED** [review]
Please would you add a test for the new message?

**Comment by 0xPoe** [comment]
> Please would you add a test for the new message?

Added.

**Review by kinnison — CHANGES_REQUESTED** [review]
Code content now looks good.  Could you please fix up your commit message now.  It is a history of everything you did and as such is not useful.

I'd suggest something along the lines of:

```
feature: include self-update status in check
```

Once the commit message is clean, I can merge this.

**Comment by 0xPoe** [comment]
> Code content now looks good. Could you please fix up your commit message now. It is a history of everything you did and as such is not useful.
> 
> I'd suggest something along the lines of:
> 
> ```
> feature: include self-update status in check
> ```
> 
> Once the commit message is clean, I can merge this.

Done, thanks for your review!

**Comment by 0xPoe** [comment]
@kinnison ping~ 😄

**Comment by kinnison** [comment]
Hi, there's still a large body in the commit message which reads like a history of the commit which isn't ideal.  I've pushed a rebase which cleans that up for you, and assuming I didn't break anything and the CI goes green, I'll merge this.  Thank you for your work on this feature.

**Comment by 0xPoe** [comment]
> Hi, there's still a large body in the commit message which reads like a history of the commit which isn't ideal. I've pushed a rebase which cleans that up for you, and assuming I didn't break anything and the CI goes green, I'll merge this. Thank you for your work on this feature.

Thanks for your review!

**Review by kinnison — APPROVED** [review]

**Pull request merged**
