### PR TITLE
fixes prompt asking for msvc even though -y is provided

### LINKED ISSUE #916: Windows confirmation prompt not disabled with -y
rustup-init.exe -y doesn't suppress all the confirmation prompts on Windows with 1.0.0.
https://github.com/rust-lang-nursery/rustup.rs/issues/912#issuecomment-271193357

### PR DESCRIPTION
**Pull request by pxdeu**
Fixes #916 
no_prompt was simply not being checked

### CODE REVIEW

**Comment by Diggsey** [comment]
@pxdeu Thanks for the PR!

I think in this case, we should still perform the MSVC check, even when `-y` is passed, but in the event that it fails, just print a warning instead of prompting the user. What do you think?

**Comment by pxdeu** [comment]
Sounds like a good idea. I thought about it when working on the issue. I only decided against it, because it would either slightly change the meaning of the function do_msvc_check (to not include the prompt) or add parameters to it.

Looking at it again, not including the prompt seems to be more in line with the rest of the code and the function is not called elsewhere as far as I can tell.

I can provide a new commit.

**Comment by Diggsey** [comment]
LGTM @bors r+

**Comment by pxdeu** [comment]
I didn't notice MSVC_MESSAGE was windows only, because I built it on windows.
Glad you have a CI in place to catch things like that.

**Pull request merged**
