### PR TITLE
increase the timeout for running `rustc --version`

### LINKED ISSUE #1312: timeout reading rustc version
On my low-end windows computer, rustup fails to print current rust version after installation with the message "timeout reading rustc version".

Indeed, there is a 3-second timeout for running `rustc --version` in rustup, but the command takes 7 seconds to complete on my computer ( 👏 windows). 

```powershell
> Measure-Command {start-process rustc -argumentlist "--version" -wait}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 7
Milliseconds      : 173
Ticks             : 71732685
TotalDays         : 8,30239409722222E-05
TotalHours        : 0,00199257458333333
TotalMinutes      : 0,119554475
TotalSeconds      : 7,1732685
TotalMilliseconds : 7173,2685
```

### PR DESCRIPTION
**Pull request by lovasoa**
Fixes #1312

### CODE REVIEW

**Comment by knight42** [comment]
I encounter this problem occasionally on my machine as well and I think it's safe to merge this PR.

**Comment by alexcrichton** [comment]
I'm sort of wary to merge this, what's causing rustc to take *10 seconds* to prints its version?

**Comment by petrochenkov** [comment]
>what's causing rustc to take 10 seconds to prints its version?

Guess: the toolchain is on a drive that's currently in low-power/low-noise mode and some wake up time is needed before `rustc` can be launched.

**Comment by Diggsey** [comment]
Couple of ideas:
- Make the time-out configurable, and if any binaries time-out, print a help message at the bottom explaining how to adjust the time-out.

- Try reading from the executable file before loading it, so we're not including the time taken to possibly spin up a drive.

**Comment by knight42** [comment]
@alexcrichton  10 secs may be too long, but 3 secs can be too short in some cases, like after a reboot:

```
>>> time rustc --version
rustc 1.24.0-nightly (b98fd524e 2018-01-05)
rustc --version  0.21s user 0.07s system 3% cpu 7.161 total
>>> time rustc --version
rustc 1.24.0-nightly (b98fd524e 2018-01-05)
rustc --version  0.18s user 0.03s system 99% cpu 0.208 total
```

**Comment by alexcrichton** [comment]
@bors: r+

Ok!

**Pull request merged**
