### PR TITLE
Update link to other installation options

### PR DESCRIPTION
**Pull request by kraai**

### CODE REVIEW

**Review by ehuss — APPROVED** [review]
Thanks!

I was also wondering if the "about" link should go to the documentation or the repo.  I was thinking the documentation might be better, since it is more user-oriented, and includes links to the repo and issue tracker on the front page.

**Comment by kraai** [comment]
@ehuss Would you like me to push another commit to this pull request or create a new pull request to update the "about" link?

**Comment by ehuss** [comment]
I have a slight preference for it to go to the documentation, but I don't feel strongly either way.  @kinnison do you have a preference where the "about" link goes?

**Comment by kinnison** [comment]
I think I'd prefer that the about link also went to the docs at https://rust-lang.github.io/rustup/ for now.  So yes, please either amend this commit, or add a second to the branch.

**Comment by kraai** [comment]
@kinnison Done.

**Comment by kinnison** [comment]
Thank you.

**Pull request merged**
