### PR TITLE
Update CHANGELOG from 1.14 upto 1.17

### LINKED ISSUE #1686: Changelog for 1.16 and 1.17
Does `rustup`  1.16 and 1.17 bring any new improments over older versions?
Those new features would be better documented in CHANGLOG.md.

### PR DESCRIPTION
**Pull request by tesuji**
Fixes #1686.

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
This LGTM.  @dwijnand ?

@lzutao - Did you create the content using a script, and if so, is it worth adding it, either to the repo or at least as a section in the CONTRIBUTING document?

**Review by dwijnand — APPROVED** [review]
Thanks!

**Comment by tesuji** [comment]
@kinnison No, I didn't use automatic script to generate CHANGELOG.

<details>

I did the following steps to manually update CHANGELOG:

* Make sure your local repository updated and had tags synced with remote:
  
  `git checkout master && git pull --tags`


* Write new tag and tag's date in format:

  ```markdown
  # [1.16.0] - 2018-12-06
  ```

  Date format is ISO-8601. Old tag date could be gotten by: `git show -s --format=%ci <tag>`.

* Checkout what's changed between old tag and new commit/tag:

  `git log --stat --graph 1.16.0...<commit/tag>`

  or use GitHub interface: https://github.com/rust-lang/rustup.rs/compare/1.16.0...master

* Filter out commits meet these conditions:

  * Typo fix
  * Small CI fix

* List all other changes in CHANGELOG:

   ```markdown
  * [Pull request name/Main content of the change](Link to pull request)
  ```

</details>

If having time, I could write an automatic script to generate CHANGELOG.

**Pull request merged**
