### PR TITLE
Adds Rust favicon

### PR DESCRIPTION
**Pull request by sl4m**
Adds favicons to minimally support Chrome, Firefox, and Safari browsers.

### CODE REVIEW

**Comment by kinnison** [comment]
Where did these image files come from?

**Comment by sl4m** [comment]
> Where did these image files come from?

From https://github.com/rust-lang/www.rust-lang.org

**Comment by kinnison** [comment]
Assuming we're allowed to cross-link with the relevant content policies etc, it may make more sense to just reference them from www.rust-lang.org then, rather than copying them over.

**Comment by sl4m** [comment]
I've updated `index.html` to just reference assets from www.rust-lang.org

**Comment by kinnison** [comment]
@pietroalbini What would it take to deploy this to dev- so that we can verify the favicons work like this?

**Comment by emilyalbini** [comment]
@kinnison we need to do the dev promotion of a release.

**Comment by kinnison** [comment]
hmm, not the easiest thing to do with a prospective change then

**Review by 4ldas — APPROVED** [review]
Seems reasonable. However could add metatags for favicons and stuff too

**Comment by kinnison** [comment]
I'm sorry it has taken so long to come back to this.  At worst if this doesn't work then it simply won't work, right?  Or will it cause browsers to complain to users?

**Comment by emilyalbini** [comment]
If this does not work I don't think users will see an explicit error from browsers. Still, we should try this out before doing the prod promotion.

**Comment by kinnison** [comment]
Okay, I'll merge this and we should remember to check it during the 1.24 release process

**Pull request merged**
