### PR TITLE
Remove header license info

### PR DESCRIPTION
**Pull request by srinivasreddy42**
https://github.com/rust-lang/rustup.rs/issues/1732

### CODE REVIEW

**Comment by kinnison** [comment]
As I said on the issue, I'm unclear why this is valuable to do.

**Comment by nrc** [comment]
I think it is reasonable to do, it brings the script file in line with the rust files (where the license boilerplate was removed along with that in the main Rust repo)

**Comment by kinnison** [comment]
@nrc Fair enough, I'll remove my mild concern then :D

**Review by kinnison — APPROVED** [review]
Based on @nrc's agreement, I withdraw my mild concern.

**Pull request merged**
