### PR TITLE
Allow current dir for component unpack

### LINKED ISSUE #2263: Can't install Rust 1.0 or 1.1 on macOS
**Problem**
When I run `rustup install 1.0.0`, it fails with:

```
info: syncing channel updates for '1.0.0-x86_64-apple-darwin'
info: downloading component 'rust'
 88.3 MiB /  88.3 MiB (100 %) 675.2 KiB/s in  2m 18s ETA:  0s    
info: installing component 'rust'
info: rolling back changes
error: tar path './._rust-1.0.0-x86_64-apple-darwin' is not supported
```

I get a similar error with installing `rustup install 1.1.0`. However, `1.2.0` works.

**Steps**
1. Run macOS 10.15 (Catalina)
2. `rustup install 1.0.0`

**Possible Solution(s)**

**Notes**

Running `which tar` reports `/usr/bin/tar`, which is a symlink to `/usr/bin/bsdtar`. I don't think this is part of the problem, but worth knowing.

Output of `rustup --version`:

```
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

Output of `rustup show`:

```
Default host: x86_64-apple-darwin
rustup home:  /Users/nvzqz/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.20.0-x86_64-apple-darwin
1.25.0-x86_64-apple-darwin
1.29.0-x86_64-apple-darwin
1.31.0-x86_64-apple-darwin
1.32.0-x86_64-apple-darwin
1.33.0-x86_64-apple-darwin
1.34.0-x86_64-apple-darwin
1.36.0-x86_64-apple-darwin
1.37.0-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.41.0 (5e1a79984 2020-01-27)
```

### PR DESCRIPTION
**Pull request by eidenar**
Fixes #2263. Simple fix as mentioned by @kinnison in the original issue.

### CODE REVIEW

**Comment by kinnison** [comment]
You have a formatting bogon (trailing comma) and I wonder if it's possible to construct at least one of the test tarballs with a `.` path component to ensure that we don't regress?

**Comment by rbtcollins** [comment]
Personally I wouldn't worry about the test path at this point - it will be a chunk of work, and we know the requirement now.

I would like a comment explaining that old tarballs have this content in them and we want to support them.

**Comment by kinnison** [comment]
Yep that's fair.  So a comment explaining so that we don't accidentally remove the support seems best.

**Comment by kinnison** [comment]
@rbtcollins I've rebased this and added the comment, how do you feel about merging this?

**Pull request merged**
