### PR TITLE
globally introduce #![deny(unreachable_pub)]

### LINKED ISSUE #2730: Detect dead code better
We should stop using 'pub' and instead use 'crate' within rustup. Rustup has no exported API, but having pub functions results in dead types and functions not being detected. https://github.com/rust-lang/rust/pull/79061 is an example of this technique applied to rustdoc

### PR DESCRIPTION
**Pull request by 0xPoe**
close https://github.com/rust-lang/rustup/issues/2730

I know we don't want to use pub(crate) in pub(crate) struct, but it looks like this lint suggests we do. Do you have any comments on how to handle it?

### CODE REVIEW

**Comment by kinnison** [comment]
I'm not sure what the right answer is here - the extra `(crate)` is entirely redundant as far as I understand it.  Perhaps we need to check in with that lint author to find out?

**Comment by 0xPoe** [comment]
@Nemo157 I remember you helped to modify this lint last year, do you have any suggestions for using create field in the crate structure? Thanks!

**Comment by Nemo157** [comment]
🤔 I did? I don't remember that. It does make sense to me that fields could be excluded from this lint, they are not _items_ which are what it's meant to lint against, but it also makes some sense to lint against them too and have a fully consistent "`pub` means external users can access it" so that locally you can tell whether things are part of the public API (though this matters less for this usecase where it looks like the `unreachable_pub` lint is being used as a manual implementation of <https://github.com/rust-lang/rust/issues/74970>).

**Comment by 0xPoe** [comment]
Maybe this doesn't make much sense for field checking. So I close it.

**Pull request closed without merging**
