### PR TITLE
Disable man support on Windows

### LINKED ISSUE #637: `rustup man cargo` fails on Windows
> d:>rustup man cargo
> thread '<main>' panicked at 'failed to open man page: Error { repr: Os { code: 2, message: "\u{41d}\u{435} \u{443}\u{434}\u{430}\u{435}\u{442}\u{441}\u{44f} \u{43d}\u{430}\u{439}\u{442}\u{438} \u{443}\u{43a}\u{430}\u{437}\u{430}\u{43d}\u{43d}\u{44b}\u{439} \u{444}\u{430}\u{439}\u{43b}." } }', ../src/libcore\result.rs:785
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> d:>set RUST_BACKTRACE=1
> 
> d:>rustup man cargo
> thread '<main>' panicked at 'failed to open man page: Error { repr: Os { code: 2, message: "\u{41d}\u{435} \u{443}\u{434}\u{430}\u{435}\u{442}\u{441}\u{44f} \u{43d}\u{430}\u{439}\u{442}\u{438} \u{443}\u{43a}\u{430}\u{437}\u{430}\u{43d}\u{43d}\u{44b}\u{439} \u{444}\u{430}\u{439}\u{43b}." } }', ../src/libcore\result.rs:785
> 
> d:>

### PR DESCRIPTION
**Pull request by kichristensen**
Disable man support on Windows.

closes #637

### CODE REVIEW

**Comment by Diggsey** [comment]
Thanks!

@bors r+

**Comment by kichristensen** [comment]
@Diggsey the test failure seems to be unrelated to this PR

**Comment by Diggsey** [comment]
ugh @bors retry

**Pull request merged**
