### PR TITLE
Do not install toolchain on `rustup show *` and `rustup --version`

### LINKED ISSUE #1397: `rustup show` should not force-install the default toolchain if it is not installed.
This behavior confused me:

```
$ rustup uninstall nightly-2018-04-01-x86_64-apple-darwin
info: uninstalling toolchain 'nightly-2018-04-01-x86_64-apple-darwin'
info: toolchain 'nightly-2018-04-01-x86_64-apple-darwin' uninstalled
$ rustup show
Default host: x86_64-apple-darwin

info: syncing channel updates for 'nightly-2018-04-01-x86_64-apple-darwin'
info: latest update on 2018-04-01, rust version 1.26.0-nightly (517f24025 2018-03-31)
info: downloading component 'rustc'
 57.3 MiB /  57.3 MiB (100 %)   7.8 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 46.2 MiB /  46.2 MiB (100 %)   7.4 MiB/s ETA:   0 s                
info: downloading component 'cargo'
  3.0 MiB /   3.0 MiB (100 %)   1.5 MiB/s ETA:   0 s                
info: downloading component 'rust-docs'
  6.8 MiB /   6.8 MiB (100 %)   3.1 MiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-i686-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-2018-04-01-x86_64-apple-darwin (directory override for '/Users/user/GitHub/unrust')
rustc 1.26.0-nightly (517f24025 2018-03-31)
```

Is `rustup show` supposed to actually start installing components? I was under the impression that it was just for listing out what you have installed.

I'm on a macOS 10.12.6 host.

### PR DESCRIPTION
**Pull request by kellda**
Fixes #1397

### CODE REVIEW

**Comment by rami3l** [comment]
@kellda Sorry for being here so late! The `rustup show` part has been addressed in https://github.com/rust-lang/rustup/pull/3225. I'd like to make you the co-author of the rest.

**Comment by kellda** [comment]
Hi,
No problem about the timing, I didn't try to push this forward either.
I'm not sure to fully understand your message. Do you expect something from me ? Do you need my approval to mark me as co-author somewhere, or should I rebase my PR to fix the rest, or something else ?

**Comment by rami3l** [comment]
@kellda Just your approval to become the co-author would be fine. We'll probably find someone else for the implementation.

**Comment by rami3l** [comment]
Superseded by #3948.

**Pull request closed without merging**
