### PR TITLE
Migrate browser opening logic to match Cargo

### PR DESCRIPTION
**Pull request by LPGhatguy**
May impact #1125.

Cargo uses the [opener](https://crates.io/crates/opener) crate for opening the user's browser. I noticed some interest in deduplicating and unifying the logic used between Rustup and Cargo in a couple places, and I think this is a reasonable part of doing that.

This PR removes about 80 lines of platform-specific code with a dependency on opener, which has no dependencies of its own. It indirectly removes an outstanding FIXME in the codebase.

### CODE REVIEW

**Comment by kinnison** [comment]
Hi,

Thank you for your contribution.  Unfortunately the CI does not pass because your code is not formatted cleanly.

Could you please rebase your change to fold the crate version commit into your main commit, and also ensure that `cargo fmt` has been run so that the formatting is clean.

Once you've done that and pushed your branch once more, I shall review it again.

Fundamentally the change looks good, but I cannot approve it until you have done this.

Thanks again,

D.

**Comment by LPGhatguy** [comment]
I formatted my change with rustfmt and went ahead and rebased + squished the commits.

**Comment by LPGhatguy** [comment]
Looks like checks are green now (I had to open/close to rerun them because of a failure installing Rust on the CI machine initially).

**Review by kinnison — APPROVED** [review]
LGTM, and this should be easy to back out if it proves not to work, though given `cargo` uses this crate it seems likely to be fine.

**Pull request merged**
