### PR TITLE
Add tab completion instructions for PowerShell

### PR DESCRIPTION
**Pull request by matt9ucci**
For Windows PowerShell and PowerShell Core (Linux/Mac/Win) users.

### CODE REVIEW

**Review by kinnison — APPROVED** [review]
I'm okay with this, but I'd like someone else who has Windows to hand to give it a :+1: too

**Comment by dwijnand** [comment]
@matt9ucci do you know if one could programmatically test installed PowerShell completions?

I'd (always) prefer a test, but I'm cool with this landing as is, and forward-fixing anything that comes up.

**Comment by matt9ucci** [comment]
>  do you know if one could programmatically test installed PowerShell completions?

Yes. 😃
Try the following test code:

```powershell
# Test rustup
if (!(Get-Command rustup)) {
    Write-Error 'rustup is not installed'
}

# Enable rustup tab completion
rustup completions powershell | Out-String | Invoke-Expression

# Get completion texts for 'rustup ' (e.g. completions, component, default, doc, etc.)
$text = 'rustup '
$cursorPosition = $text.Length
$options = $null
$completionTexts = [System.Management.Automation.CommandCompletion]::CompleteInput($text, $cursorPosition, $options).CompletionMatches.CompletionText

# Verify the result of completion
if ($completionTexts -contains 'completions') {
    Write-Host 'rustup tab completion is successfully enabled'
} else {
    Write-Error 'rustup tab completion is not enabled'
}
```

It is just an easy version. If we need "full" unit testing, using the [Pester](https://github.com/pester/Pester) is the best solution (for reference, see [my Pester test cases for DockerCompletion module](https://github.com/matt9ucci/DockerCompletion/blob/master/Tests/DockerCompletion.Tests.ps1))

**Comment by dwijnand** [comment]
Cool.  It doesn't look like we have anything like that running on AppVeyor.  Is setting that up something that would be of interest to you?

**Comment by kinnison** [comment]
I'm not sure we CI completions at all right now.  I'd be satisfied with just one other person who *can* use PowerShell verifying that the instructions provided for the README work and are appropriately idiomatic.

**Comment by matt9ucci** [comment]
Hi all. I have done with Pester test script and appveyor.yml, and submitted the PR #1629. Please review it.
If you do not need such a test script, don't hesitate to close the PR.

**Pull request merged**
