### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by djc — COMMENTED** [review]
"won't be doing" seems more currect to me than "aren't be doing"?

**Review by xen0n — COMMENTED** [review]
Here "[you] won't be doing ..." means "[you] are not going to do ... in the short term / in the foreseeable future", while "[you] aren't doing ..." sounds more like "[you] will not do ... right now / at all". So I personally feel the original text sounds more natural.

Mandatory disclaimer though: I'm not a native speaker of English.

**Comment by ghost** [comment]
> "won't be doing" seems more currect to me than "aren't be doing"?

Yes, that’s what I meant. I guess that’s what I get for making a PR at 2AM xD

**Comment by ghost** [comment]
Okay this is strange. I created a PR to fix this a couple months ago and it was merged. It seems like the docs themselves haven’t updated with that PR yet, so ignore this one.

**Pull request closed without merging**
