### PR TITLE
Replace deprecated tempdir with tempfile

### PR DESCRIPTION
**Pull request by tesuji**

### CODE REVIEW

**Comment by kinnison** [comment]
Fundamentally I'm good with this, though there are test failures, so please resolve those before I review deeply.

**Comment by tesuji** [comment]
```
failures:
---- remove_toolchain_then_add_again stdout ----
thread 'remove_toolchain_then_add_again' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1142, kind: Other, message: "An attempt was made to create more links on a file than the file system supports." }', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I'm now convinced that something on our side has messed up.

**Comment by kinnison** [comment]
Hey @lzutao Could you rebase this against current master and see how it looks?

**Review by kinnison — APPROVED** [review]
I *think* this is okay.  I'd like a second opinion before merge.

**Review by rbtcollins — APPROVED** [review]
I don't like the new API so much, I have to say.

**Pull request merged**
