### PR TITLE
Enable building doc again

### PR DESCRIPTION
**Pull request by tesuji**
Demo is at https://lzutao.github.io/rustup.rs .

### CODE REVIEW

**Comment by kinnison** [comment]
I'm not anxious for this, not least because it implies content on rust-lang.github.io which is stuff we're not at all intending to support as an external API.  What's your rationale for wanting this?

**Comment by tesuji** [comment]
Maybe we should ask @brson, [he was the one who disabled uploading docs](https://github.com/rust-lang/rustup.rs/commit/be86e1f7731785e0ef5718678914d16f8d8699d4).

**Comment by tesuji** [comment]
Ping @brson , do you have any thoughts on this PR?

**Comment by kinnison** [comment]
Until and unless we intend to improve internal code documentation to help new hackers on rustup, I don't think this is worthwhile since it might encourage people to think we support them linking to rustup code in their own projects, which we really don't want to do.

**Comment by nrc** [comment]
I think I agree with @kinnison - we don't want to give the impression that using Rustup as a library is OK. It's easy enough for devs to do `cargo doc --open`, I don't see much advantage in publishing docs.

Sorry, and thanks for the PR!

**Pull request closed without merging**
