### PR TITLE
Build for aarch64-apple-darwin

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by kinnison** [comment]
The macos changes need to go in the actions template, otherwise they'll be lost next time we regenerate the actions files.  Also I think the set-env stuff needs changing now :D

**Comment by shepmaster** [comment]
Ah, I was waiting for https://github.com/rust-lang/rustup/issues/2515 and it looks like it’s been addressed.

**Comment by shepmaster** [comment]
> The macos changes need to go in the actions template

Done.

> the set-env stuff needs changing now

Done.

**Comment by kinnison** [comment]
As a final point before I merge this, have you confirmed that `rustup` believes this is a valid *host* triple?

**Comment by kinnison** [comment]
I think it should do, and I seem to recall you running your cross-built binary on an aarch64 mac, but I just want to be sure

**Comment by shepmaster** [comment]
> have you confirmed that `rustup` believes this is a valid _host_ triple?

If I understand you, I think so. `rustup` actually [works “as-is” today](https://github.com/shepmaster/rust/blob/silicon/silicon/README.md#compiling-on-native-aarch64-hardware):

> ```
> arch --x86_64 \
> sh <(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) \
> --default-host aarch64-apple-darwin \
> --default-toolchain nightly
> ```

I expect that this PR removes the need to bring in the x86-64 emulator. A future change to the shell script should reduce it to the usual one-liner.

**Pull request merged**
