### PR TITLE
Add docs command

### LINKED ISSUE #928: Add "rustup docs" command alias for "rustup doc"
The error message does suggest `doc`, so this isn't necessary, but I type it regularly and I wonder if others share my pain.
```
$ rustup docs
error: The subcommand 'docs' wasn't recognized
        Did you mean 'doc'?

If you believe you received this message in error, try re-running with 'rustup -- docs'

USAGE:
    rustup [FLAGS] [SUBCOMMAND]

For more information try --help
```

### PR DESCRIPTION
**Pull request by topecongiro**
Add an alias of "rustup doc".
Closes #928.

### CODE REVIEW

**Comment by kbknapp** [comment]
It would probably be better to make `docs` [an alias](https://docs.rs/clap/2.22.1/clap/struct.App.html#method.alias) for the `doc` command instead of duplicating the command. There's also some discussion in #980

**Comment by topecongiro** [comment]
@kbknapp Thank you for your comment.
Rebased.

**Comment by topecongiro** [comment]
I am sorry, I just pushed the commit for other PR...
Fixed it.

**Pull request merged**
