### PR TITLE
Add rust-analyzer proxy

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by kinnison** [comment]
I've added the proxy to the snapcraft bit too, I forgot to mention that earlier on discord.

**Review by kinnison — APPROVED** [review]

**Comment by akurtakov** [comment]
Is this change visible for users on nightly channel?

**Comment by rbtcollins** [comment]
We need to cut a release before this will become visible to rustup users.

**Comment by akurtakov** [comment]
Any hope for new release?

**Comment by kinnison** [comment]
I'm afraid with everything going on in the world, I've been too busy to cut a release.  I'll be looking to do so in the near future though.

**Comment by akurtakov** [comment]
Too bad this one didn't make it to 1.23.0 release.

**Comment by kinnison** [comment]
This was explicitly backed out for 1.23.0 because rust-analyzer isn't going to be in `stable` for a while.

**Comment by akurtakov** [comment]
So there is not a chance to have the proxy for nightly only for now?

**Comment by kinnison** [comment]
Proxies are installed into PATH so it's not possible to only provide a proxy for one toolchain, no.  When we have a closer timeline for the component making it to stable we'll put the proxy back in.

**Comment by kinnison** [comment]
You *can* make the link yourself, and then `rust-analyzer +nightly` ought to work; but it's not ideal.

**Pull request merged**
