### PR TITLE
Add x86_64-linux-android target

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by malbarbo** [comment]
The travis rust update is necessary because x86_64-linux-android target was recently added. The nightly channel is not necessary, using the beta channel would be enough.

**Comment by brson** [comment]
This looks great @malbarbo. Since this updates the pinned toolchain for travis, will you also update the same in appveyor.yml?

**Comment by malbarbo** [comment]
@brson I update the toolchain in appveyor.yml.

**Comment by malbarbo** [comment]
@brson Added a missing case in rustup-dist. Sorry for missing that.

**Pull request merged**
