### PR TITLE
Retry to install proxies during already up-to-date self update

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/rust-lang-nursery/rustup.rs/issues/1305, which this hopefully fixes.

### CODE REVIEW

**Comment by SimonSapin** [comment]
I expected this to fail before this PR, but it already passes. So I don’t know if this PR actually fixes the problem.

```diff
diff --git a/tests/cli-self-upd.rs b/tests/cli-self-upd.rs
index c8bc9c4b..3a24f93a 100644
--- a/tests/cli-self-upd.rs
+++ b/tests/cli-self-upd.rs
@@ -1273,5 +1273,12 @@ fn update_does_not_overwrite_rustfmt() {
                          "`rustfmt` is already installed");
         assert!(rustfmt_path.exists());
         assert_eq!(utils::file_size(rustfmt_path).unwrap(), 0);
+
+        // Remove the file as suggested by the error "already installed" error message.
+        utils::remove_file("rustfmt", rustfmt_path).unwrap();
+        assert!(!rustfmt_path.exists());
+
+        expect_ok(config, &["rustup", "self", "update"]);
+        assert!(rustfmt_path.exists());
     });
 }

**Comment by alexcrichton** [comment]
@SimonSapin it looks like the failures on CI may be related?

**Comment by SimonSapin** [comment]
Fixed.

**Comment by alexcrichton** [comment]
@SimonSapin it looks like unfortunately this causes what I think is perhaps more buggy behavior?

Now every time I type `rustup update` it looks like rustup unconditionally downloads an update and then installs it (for itself).

**Comment by SimonSapin** [comment]
Could you say more, maybe copy/paste the output? This PR hasn’t changed the code in `prepare_update()` that skips the download when `available_version == current_version`.

**Comment by alexcrichton** [comment]
Every self update looks like

```
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.8.0
```

and every update looks like:

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'beta-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates
info: downloading self-update

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.22.1 (05e2e1c41 2017-11-22)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.23.0-beta.2 (c9107ee93 2017-12-08)
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.24.0-nightly (dc39c3169 2017-12-17)
```

where strace confirms the latter is indeed downloading/relinking rustup.

**Comment by SimonSapin** [comment]
https://static.rust-lang.org/rustup/release-stable.toml contains `version = '1.7.0'`, https://dev-static.rust-lang.org/rustup/release-stable.toml contains `version = '--live-run'`.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang-nursery/rustup.rs/pull/1315

**Comment by alexcrichton** [comment]
Urgh well that's a bummer :(

Thanks for taking a look!

**Comment by alexcrichton** [comment]
Hm that doesn't seem to have fixed the issue though?

**Comment by alexcrichton** [comment]
Hm no wait hang on, that may be a cloudfront caching issue

**Comment by alexcrichton** [comment]
Deployed!

**Comment by cbcoutinho** [comment]
I'm having this issue as well. At the last `rustup update` I got a warning to remove `rustfmt` and `cargo-fmt`, which I did using cargo uninstall rustfmt

Executing `rustup update` does nothing. Further I still have executables in `.cargo/bin`, for `rustfmt` and `cargo-fmt`. If this fix is only checking for he existence of those then it doesn't work.

Launching `rustfmt` results in the following error:

```shell
$ rustfmt
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not have the binary `rustfmt`
```

I get the same error for nightly

**Comment by alexcrichton** [comment]
@cbcoutinho that's actually expected (albeit not a great error message)

You'll need to add the rustup component like so:

```
$ rustup component add rustfmt-preview --toolchain nightly
```

and then you can execute it via `rustfmt +nightly ...`

**Comment by brendanzab** [comment]
Hmm, I tried this on macOS, but no luck:

```
λ rustup component add rustfmt-preview --toolchain nightly
error: toolchain 'nightly-x86_64-apple-darwin' does not contain component 'rustfmt-preview' for target 'x86_64-apple-darwin'
```

**Comment by brendanzab** [comment]
Oh, I'm guessing this might be because of a build failure? I seem to be missing rls as well since I ran `rustup update`:

```
λ rustup component add rls-preview --toolchain nightly
error: toolchain 'nightly-x86_64-apple-darwin' does not contain component 'rls-preview' for target 'x86_64-apple-darwin'
```

**Comment by brendanzab** [comment]
`nightly-2017-12-20` worked for me:

```
rustup toolchain install nightly-2017-12-20
rustup component add rust-analysis --toolchain nightly-2017-12-20
rustup component add rust-src --toolchain nightly-2017-12-20
rustup component add rls-preview --toolchain nightly-2017-12-20
rustup component add rustfmt-preview --toolchain nightly-2017-12-20
```

**Comment by olson-dan** [comment]
Note that this PR is alleged to have caused #1316

**Pull request merged**
