### PR TITLE
Aggressive remove_dir_all

### PR DESCRIPTION
**Pull request by brson**
Let's see if this helps the flakiness.

cc @Diggsey @alexcrichton 

cc @Aaronepower this PR contains a self-contained remove_dir_all module based on winapi.

### CODE REVIEW

**Comment by Diggsey** [comment]
Looks like we might need an aggressive `remove_file` too...

**Comment by alexcrichton** [comment]
I personally forget, but can you clarify how precisely this is more aggressive again?

**Comment by Diggsey** [comment]
It moves the files out of the subdirectory and up next to the directory being deleted, prior to deleting them. This means if the file deletion is delayed due to outstanding locks, then the directories can still be deleted successfully without waiting for other processes to close their file handles.

The failure here looks different - like a race condition in one of the self-updater tests possibly?

**Comment by brson** [comment]
Updated to fix the linux build hopefully.

**Comment by brson** [comment]
Test failure was network error and i want to deploy this in next release.

**Pull request merged**
