### PR TITLE
Fixing janky line breaks in self_updater.rs

### PR DESCRIPTION
**Pull request by rbtcollins**
Fixing janky line breaks in the %USERPROFILE% path help string, as reported in #2334

### CODE REVIEW

**Comment by kinnison** [comment]
Did this come from #2336 ?  if so, why not just update that MR.  As a rustup committer you should have had the rights.

**Comment by rbtcollins** [comment]
> 
> 
> Did this come from #2336 ? if so, why not just update that MR. As a rustup committer you should have had the rights.

That capability is able to be turned on and off on a per PR basis... yes it is that PR rebased. I'm not sure how to update that PR.

**Comment by kinnison** [comment]
If you can, it'll say near the bottom of the page (above the checks/merge box) 'Add more commits by pushing to ...'

**Comment by kinnison** [comment]
OOI did this get done somewhere, or should we merge this?

**Pull request merged**
