### PR TITLE
Remove dead code warning for test-only `size` field for `diskio::Item`

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Comment by 0xPoe** [comment]
We use it in our tests. Maybe we can use cfg(test).

I seem to have missed it in https://github.com/rust-lang/rustup/pull/2901.

**Comment by jyn514** [comment]
Ah, ok. I can add `cfg(test)` to it instead.

**Review by 0xPoe — APPROVED** [review]
LGTM. Thanks!

**Comment by rbtcollins** [comment]
Thank you for fixing this. I"m a bit nervous about our test coverage here, but we can always iterate with other patches in future.

**Pull request merged**
