### PR TITLE
Print default toolchain on `rustup default` without arguments

### PR DESCRIPTION
**Pull request by das-sein**
Implementation of #1632 

Behavior: When `rustup default` is not provided arguments, print the default toolchain (new behavior) before commencing updates of all installed toolchains.

### CODE REVIEW

**Comment by dwijnand** [comment]
Hey, @lazorgator.  Thanks for sending the PR.  Want to update the tests so we can assess how this implementation behaves?

**Comment by das-sein** [comment]
Yep, sorry about that! Working on them now for both PRs.

**Comment by das-sein** [comment]
@dwijnand Should be all set. I only needed to modify one test. However, I noticed that it was possible to be in a state wherein no default toolchain was set in the settings. This required modification of the `config.get_default()` behavior very slightly. It doesn't seem to affect how the rest of the software expects that method to work. Without the modification it would throw an exception about trying to `unwrap()` a None during the `rustup_self_update_exact` test.

**Review by dwijnand — APPROVED** [review]
Thanks, @lazorgator.  The patch seems reasonable to me.  I'd merge it if I could.  So let's see if this matches @nrc's expectations in #1632.

**Comment by lazorgator** [comment]
Sorry for force push. Accidentally pushed a README change meant for the component filtering PR. As with any history rewrite, I must state that I am a bad person lol.

**Comment by nrc** [comment]
I'm very sorry, but I messed up and wrote `update` when I meant `default` in #1632 . Could you change this PR to printing the same message but on the different command please?

**Comment by lazorgator** [comment]
@nrc All good, will do. Should I keep this in the same PR and simply change the name of it? Also, should I keep this in a new commit or do you prefer squashed?

**Comment by das-sein** [comment]
@nrc Alright, added the functionality to `rustup default` as well! If you want me to remove the functionality from `rustup update`, let me know.

**Comment by dwijnand** [comment]
Perhaps it's best to remove it from `rustup update`.

**Comment by das-sein** [comment]
@dwijnand @nrc Should be all set, I think. Functionality removed from `rustup update`.

**Review by dwijnand — APPROVED** [review]
Re-LGTM

**Comment by nrc** [comment]
Awesome, thanks!

**Comment by dwijnand** [comment]
Does this duplicate `rustup show active-toolchain`?

**Comment by das-sein** [comment]
@dwijnand It does I think! I'll work on a PR to just make the `rustup default` behavior an alias to that command, if possible. `rustup show active-toolchain` also deals with the override display issue.

**Pull request merged**
