### PR TITLE
Edit .bash_profile if it exists

### LINKED ISSUE #883: PATH to cargo/bin is in wrong file, should be in .bash_profile (CentOS)
CentOS is default AWS EC2 version of Linux, please consider to add path into .bash_profile also, at least if this file exist.

### PR DESCRIPTION
**Pull request by awelkie**
Fixes #883

### CODE REVIEW

**Comment by Diggsey** [comment]
Hi @awelkie, this looks great.

I would like to slightly alter the detection logic here, specifically:
- Modify `.zprofile` if *either* it already exists, *or* the shell is zsh
- Modify `.bash_profile` only if it exists, regardless of the current shell

IMO, this would provide the best result given each shell's profile logic.

However, I'd be happy to accept this PR as-is if you won't be able to make these changes, since it's a clear improvement over the status quo, and shouldn't cause any problems to tweak later.

**Comment by brson** [comment]
@Diggsey's suggestion sounds reasonable to me. Thanks @awelkie!

**Comment by awelkie** [comment]
I'll take a crack at making these changes. I would also like to add support for fish (#478). Should the logic there be to add add a file to ~/.config/fish/conf.d only if ~/.config/fish/ exists, regardless of the current shell?

**Comment by Diggsey** [comment]
@awelkie Thanks!

For all shells except bash, we should set their configuration if we detect their presence at all on the system. For the moment, the two detection methods we use are `$SHELL` and whether their configuration files are detected.

Bash is different, because it will fall back to `.profile` if `.bash_profile` does not exist, so even if `$SHELL == "bash"`, we can't create `.bash_profile` if it doesn't already exist, as then bash would stop looking in `.profile`, which would break things for the user.

So for fish, we want to add a file to `~/.config/fish/conf.d` if *either* the fish config directory already exists, *or* if fish is the current shell.

**Comment by awelkie** [comment]
I don't think I'll be able to get to the making the improvements for another few days, so feel free to merge this in if you want.

**Comment by brson** [comment]
For this PR I agree that at least it would be better to remove reading "SHELL" and just look for the presense of .bash_profile. zsh changes can be left for some other PR.

This should really also have a test case. Crib off of "install_adds_path_to_profile".

**Comment by brson** [comment]
I've updated this in #1179.

**Pull request closed without merging**
