### PR TITLE
Indent help text

### LINKED ISSUE #940: Improve indentation of help
I find the indentation of command like `rustup override` very confusing

```
$ rustup override
rustup-override 
Modify directory toolchain overrides

USAGE:
    rustup override [SUBCOMMAND]

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    list     List directory toolchain overrides
    set      Set the override toolchain for a directory
    unset    Remove the override toolchain for a directory
    help     Prints this message or the help of the given subcommand(s)


Overrides configure rustup to use a specific toolchain when
running in a specific directory.

Directories can be assigned their own Rust toolchain with
`rustup override`. When a directory has an override then
any time `rustc` or `cargo` is run inside that directory,
or one of its child directories, the override toolchain
will be invoked.

To pin to a specific nightly:

    rustup override set nightly-2014-12-18

Or a specific stable release:

    rustup override set 1.0.0
$ _
```

At first glance it looks roughly like this
```
$ rustup override
      ... something indented
a lot of unindented text. a lot of text. a lot of text.
a lot of unindented text. a lot of text. a lot of text.
      ... something indented again
$ _
```

I find that extremely unreadable due to the mix of indented and unindented chunks.
I suggest to adopt the structure of a manpage, i.e. everything is indented except for headlines, which are uppercase.

The example above could look like this

```
$ rustup override
NAME:
    rustup-override

DESCRIPTION:
    Modify directory toolchain overrides

USAGE:
    rustup override [SUBCOMMAND]

FLAGS:
    -h, --help    Prints help information

SUBCOMMANDS:
    list     List directory toolchain overrides
    set      Set the override toolchain for a directory
    unset    Remove the override toolchain for a directory
    help     Prints this message or the help of the given subcommand(s)

DISCUSSION:
    Overrides configure rustup to use a specific toolchain when
    running in a specific directory.

    Directories can be assigned their own Rust toolchain with
    `rustup override`. When a directory has an override then
    any time `rustc` or `cargo` is run inside that directory,
    or one of its child directories, the override toolchain
    will be invoked.

    To pin to a specific nightly:

        rustup override set nightly-2014-12-18

    Or a specific stable release:

        rustup override set 1.0.0
$ _
```

=> Much better IMO. Now I can immediately see what belongs where. :-)
What do you think about this suggestion?

### PR DESCRIPTION
**Pull request by babbageclunk**
Add a DISCUSSION heading to each item and indent (and rewrap) the help text.

Fixes #940.

### CODE REVIEW

**Comment by brson** [comment]
Thanks @babbageclunk!

@kbknapp I wonder if you can peek at this and suggest whether it's the right way. My understanding of this issue is that we are trying to imitate claps generated formatting manually. Can clap itself produce formatting like this for these freeform text bits.

**Comment by kbknapp** [comment]
@brson Unfortunately this is the best way at this time. 

The `after_help` portion is designed to be free-form and thus all headers and formatting are left to users. The only thing that `after_help` *does do* is rewrap properly at word boundaries. But since rustup is already using hard newline wrapping this isn't really an issue. 

With the current PR, if someone has a terminal window with < 70 (I think?) columns the rewrapping that clap will do won't respect the hard tabs (or 4x spaces). However, someone with a terminal window that small is probably a rare-ish occurrence.

I'm open to someone adding the ability for clap to respect the starting indentation when using [`template`](https://docs.rs/clap/2.22.2/clap/struct.App.html#method.template)s, and would be willing to mentor such efforts. I just don't have time to implement it myself at the moment. This would be the best solution as then all rewrapping and indentation is handled by clap.

**Comment by Diggsey** [comment]
Let's do this for now, we can always improve it later if we find a better way.

@bors r+

**Comment by babbageclunk** [comment]
Oh, nice! I guess that was a flaky test?

**Comment by Diggsey** [comment]
Just a network error, yeah.

**Pull request merged**
