### PR TITLE
Update links and install page to include android support

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by brson** [comment]
@bors r+

@malbarbo Can I ask you to make the equivalent change to https://github.com/rust-lang/rust-www?

**Comment by brson** [comment]
Oh, yikes, this modifies html so the equivalent www change is going to touch every translation. Sorry :(

**Comment by malbarbo** [comment]
Done: https://github.com/rust-lang/rust-www/pull/775.

**Comment by brson** [comment]
Oh there's nothing testable here, just merging.

**Pull request merged**
